/*
node-flow

Testing MetadataAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package nodeflow

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/node-flow/node-flow-go/nodeflow"
)

func Test_nodeflow_MetadataAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MetadataAPIService MetadataDeleteTaskDefinition", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var name string

		resp, httpRes, err := apiClient.MetadataAPI.MetadataDeleteTaskDefinition(context.Background(), ns, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MetadataAPIService MetadataDeleteWorkflow", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var name string

		resp, httpRes, err := apiClient.MetadataAPI.MetadataDeleteWorkflow(context.Background(), ns, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MetadataAPIService MetadataExportBundle", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string

		resp, httpRes, err := apiClient.MetadataAPI.MetadataExportBundle(context.Background(), ns).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MetadataAPIService MetadataGetTaskDefinition", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var name string

		resp, httpRes, err := apiClient.MetadataAPI.MetadataGetTaskDefinition(context.Background(), ns, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MetadataAPIService MetadataGetWorkflow", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var name string

		resp, httpRes, err := apiClient.MetadataAPI.MetadataGetWorkflow(context.Background(), ns, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MetadataAPIService MetadataImportBpmnDocument", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string

		resp, httpRes, err := apiClient.MetadataAPI.MetadataImportBpmnDocument(context.Background(), ns).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MetadataAPIService MetadataImportBundle", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string

		resp, httpRes, err := apiClient.MetadataAPI.MetadataImportBundle(context.Background(), ns).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MetadataAPIService MetadataListTaskDefinitions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string

		resp, httpRes, err := apiClient.MetadataAPI.MetadataListTaskDefinitions(context.Background(), ns).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MetadataAPIService MetadataListWorkflows", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string

		resp, httpRes, err := apiClient.MetadataAPI.MetadataListWorkflows(context.Background(), ns).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MetadataAPIService MetadataRegisterWorkflow", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string

		resp, httpRes, err := apiClient.MetadataAPI.MetadataRegisterWorkflow(context.Background(), ns).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MetadataAPIService MetadataSetWorkflowTags", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var name string

		resp, httpRes, err := apiClient.MetadataAPI.MetadataSetWorkflowTags(context.Background(), ns, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MetadataAPIService MetadataUpsertTaskDefinition", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string

		resp, httpRes, err := apiClient.MetadataAPI.MetadataUpsertTaskDefinition(context.Background(), ns).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MetadataAPIService MetadataValidateWorkflow", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string

		resp, httpRes, err := apiClient.MetadataAPI.MetadataValidateWorkflow(context.Background(), ns).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MetadataAPIService SimulationTest", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string

		resp, httpRes, err := apiClient.MetadataAPI.SimulationTest(context.Background(), ns).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
