/*
node-flow

Testing QuotasAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package nodeflow

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/node-flow/node-flow-go/nodeflow"
)

func Test_nodeflow_QuotasAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test QuotasAPIService QuotaGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string

		resp, httpRes, err := apiClient.QuotasAPI.QuotaGet(context.Background(), ns).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test QuotasAPIService QuotaSet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string

		resp, httpRes, err := apiClient.QuotasAPI.QuotaSet(context.Background(), ns).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
