/*
node-flow

Testing HumanTasksAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package nodeflow

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/node-flow/node-flow-go/nodeflow"
)

func Test_nodeflow_HumanTasksAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test HumanTasksAPIService HumanTaskClaim", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var id string

		resp, httpRes, err := apiClient.HumanTasksAPI.HumanTaskClaim(context.Background(), ns, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HumanTasksAPIService HumanTaskComplete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var id string

		resp, httpRes, err := apiClient.HumanTasksAPI.HumanTaskComplete(context.Background(), ns, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HumanTasksAPIService HumanTaskGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var id string

		resp, httpRes, err := apiClient.HumanTasksAPI.HumanTaskGet(context.Background(), ns, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HumanTasksAPIService HumanTaskInbox", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string

		resp, httpRes, err := apiClient.HumanTasksAPI.HumanTaskInbox(context.Background(), ns).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HumanTasksAPIService HumanTaskReassign", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var id string

		resp, httpRes, err := apiClient.HumanTasksAPI.HumanTaskReassign(context.Background(), ns, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HumanTasksAPIService HumanTaskRelease", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var id string

		resp, httpRes, err := apiClient.HumanTasksAPI.HumanTaskRelease(context.Background(), ns, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HumanTasksAPIService HumanTaskSearch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string

		resp, httpRes, err := apiClient.HumanTasksAPI.HumanTaskSearch(context.Background(), ns).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HumanTasksAPIService HumanTaskSkip", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var id string

		resp, httpRes, err := apiClient.HumanTasksAPI.HumanTaskSkip(context.Background(), ns, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
