/*
node-flow

Testing SchedulesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package nodeflow

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/node-flow/node-flow-go/nodeflow"
)

func Test_nodeflow_SchedulesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SchedulesAPIService ScheduleCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string

		resp, httpRes, err := apiClient.SchedulesAPI.ScheduleCreate(context.Background(), ns).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchedulesAPIService ScheduleGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var name string

		resp, httpRes, err := apiClient.SchedulesAPI.ScheduleGet(context.Background(), ns, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchedulesAPIService ScheduleList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string

		resp, httpRes, err := apiClient.SchedulesAPI.ScheduleList(context.Background(), ns).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchedulesAPIService SchedulePause", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var name string

		resp, httpRes, err := apiClient.SchedulesAPI.SchedulePause(context.Background(), ns, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchedulesAPIService SchedulePreview", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string

		resp, httpRes, err := apiClient.SchedulesAPI.SchedulePreview(context.Background(), ns).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchedulesAPIService ScheduleRemove", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var name string

		httpRes, err := apiClient.SchedulesAPI.ScheduleRemove(context.Background(), ns, name).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchedulesAPIService ScheduleResume", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var name string

		resp, httpRes, err := apiClient.SchedulesAPI.ScheduleResume(context.Background(), ns, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchedulesAPIService ScheduleRuns", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var name string

		resp, httpRes, err := apiClient.SchedulesAPI.ScheduleRuns(context.Background(), ns, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchedulesAPIService ScheduleUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var name string

		resp, httpRes, err := apiClient.SchedulesAPI.ScheduleUpdate(context.Background(), ns, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
