/*
node-flow

Testing SchemasAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package nodeflow

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/node-flow/node-flow-go/nodeflow"
)

func Test_nodeflow_SchemasAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SchemasAPIService SchemaList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string

		resp, httpRes, err := apiClient.SchemasAPI.SchemaList(context.Background(), ns).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchemasAPIService SchemaRegister", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string

		resp, httpRes, err := apiClient.SchemasAPI.SchemaRegister(context.Background(), ns).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchemasAPIService SchemaRemove", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var name string

		httpRes, err := apiClient.SchemasAPI.SchemaRemove(context.Background(), ns, name).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchemasAPIService SchemaValidate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var name string

		resp, httpRes, err := apiClient.SchemasAPI.SchemaValidate(context.Background(), ns, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchemasAPIService SchemaVersions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ns string
		var name string

		resp, httpRes, err := apiClient.SchemasAPI.SchemaVersions(context.Background(), ns, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
