/*
node-flow

Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nodeflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VectorIndexSearchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VectorIndexSearchRequest{}

// VectorIndexSearchRequest struct for VectorIndexSearchRequest
type VectorIndexSearchRequest struct {
	LlmProvider string `json:"llmProvider"`
	EmbeddingModel *string `json:"embeddingModel,omitempty"`
	Query string `json:"query"`
	TopK *int32 `json:"topK,omitempty"`
	MinScore *float32 `json:"minScore,omitempty"`
}

type _VectorIndexSearchRequest VectorIndexSearchRequest

// NewVectorIndexSearchRequest instantiates a new VectorIndexSearchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVectorIndexSearchRequest(llmProvider string, query string) *VectorIndexSearchRequest {
	this := VectorIndexSearchRequest{}
	this.LlmProvider = llmProvider
	this.Query = query
	return &this
}

// NewVectorIndexSearchRequestWithDefaults instantiates a new VectorIndexSearchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVectorIndexSearchRequestWithDefaults() *VectorIndexSearchRequest {
	this := VectorIndexSearchRequest{}
	return &this
}

// GetLlmProvider returns the LlmProvider field value
func (o *VectorIndexSearchRequest) GetLlmProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LlmProvider
}

// GetLlmProviderOk returns a tuple with the LlmProvider field value
// and a boolean to check if the value has been set.
func (o *VectorIndexSearchRequest) GetLlmProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LlmProvider, true
}

// SetLlmProvider sets field value
func (o *VectorIndexSearchRequest) SetLlmProvider(v string) {
	o.LlmProvider = v
}

// GetEmbeddingModel returns the EmbeddingModel field value if set, zero value otherwise.
func (o *VectorIndexSearchRequest) GetEmbeddingModel() string {
	if o == nil || IsNil(o.EmbeddingModel) {
		var ret string
		return ret
	}
	return *o.EmbeddingModel
}

// GetEmbeddingModelOk returns a tuple with the EmbeddingModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorIndexSearchRequest) GetEmbeddingModelOk() (*string, bool) {
	if o == nil || IsNil(o.EmbeddingModel) {
		return nil, false
	}
	return o.EmbeddingModel, true
}

// HasEmbeddingModel returns a boolean if a field has been set.
func (o *VectorIndexSearchRequest) HasEmbeddingModel() bool {
	if o != nil && !IsNil(o.EmbeddingModel) {
		return true
	}

	return false
}

// SetEmbeddingModel gets a reference to the given string and assigns it to the EmbeddingModel field.
func (o *VectorIndexSearchRequest) SetEmbeddingModel(v string) {
	o.EmbeddingModel = &v
}

// GetQuery returns the Query field value
func (o *VectorIndexSearchRequest) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *VectorIndexSearchRequest) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *VectorIndexSearchRequest) SetQuery(v string) {
	o.Query = v
}

// GetTopK returns the TopK field value if set, zero value otherwise.
func (o *VectorIndexSearchRequest) GetTopK() int32 {
	if o == nil || IsNil(o.TopK) {
		var ret int32
		return ret
	}
	return *o.TopK
}

// GetTopKOk returns a tuple with the TopK field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorIndexSearchRequest) GetTopKOk() (*int32, bool) {
	if o == nil || IsNil(o.TopK) {
		return nil, false
	}
	return o.TopK, true
}

// HasTopK returns a boolean if a field has been set.
func (o *VectorIndexSearchRequest) HasTopK() bool {
	if o != nil && !IsNil(o.TopK) {
		return true
	}

	return false
}

// SetTopK gets a reference to the given int32 and assigns it to the TopK field.
func (o *VectorIndexSearchRequest) SetTopK(v int32) {
	o.TopK = &v
}

// GetMinScore returns the MinScore field value if set, zero value otherwise.
func (o *VectorIndexSearchRequest) GetMinScore() float32 {
	if o == nil || IsNil(o.MinScore) {
		var ret float32
		return ret
	}
	return *o.MinScore
}

// GetMinScoreOk returns a tuple with the MinScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorIndexSearchRequest) GetMinScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.MinScore) {
		return nil, false
	}
	return o.MinScore, true
}

// HasMinScore returns a boolean if a field has been set.
func (o *VectorIndexSearchRequest) HasMinScore() bool {
	if o != nil && !IsNil(o.MinScore) {
		return true
	}

	return false
}

// SetMinScore gets a reference to the given float32 and assigns it to the MinScore field.
func (o *VectorIndexSearchRequest) SetMinScore(v float32) {
	o.MinScore = &v
}

func (o VectorIndexSearchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VectorIndexSearchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["llmProvider"] = o.LlmProvider
	if !IsNil(o.EmbeddingModel) {
		toSerialize["embeddingModel"] = o.EmbeddingModel
	}
	toSerialize["query"] = o.Query
	if !IsNil(o.TopK) {
		toSerialize["topK"] = o.TopK
	}
	if !IsNil(o.MinScore) {
		toSerialize["minScore"] = o.MinScore
	}
	return toSerialize, nil
}

func (o *VectorIndexSearchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"llmProvider",
		"query",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVectorIndexSearchRequest := _VectorIndexSearchRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVectorIndexSearchRequest)

	if err != nil {
		return err
	}

	*o = VectorIndexSearchRequest(varVectorIndexSearchRequest)

	return err
}

type NullableVectorIndexSearchRequest struct {
	value *VectorIndexSearchRequest
	isSet bool
}

func (v NullableVectorIndexSearchRequest) Get() *VectorIndexSearchRequest {
	return v.value
}

func (v *NullableVectorIndexSearchRequest) Set(val *VectorIndexSearchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVectorIndexSearchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVectorIndexSearchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVectorIndexSearchRequest(val *VectorIndexSearchRequest) *NullableVectorIndexSearchRequest {
	return &NullableVectorIndexSearchRequest{value: val, isSet: true}
}

func (v NullableVectorIndexSearchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVectorIndexSearchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


