/*
node-flow

Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nodeflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Shared2d711327d8SubWorkflowParam type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Shared2d711327d8SubWorkflowParam{}

// Shared2d711327d8SubWorkflowParam struct for Shared2d711327d8SubWorkflowParam
type Shared2d711327d8SubWorkflowParam struct {
	Name string `json:"name" validate:"regexp=^[a-zA-Z_][a-zA-Z0-9_.-]*$"`
	Version *int32 `json:"version,omitempty"`
	TaskToDomain map[string]string `json:"taskToDomain,omitempty"`
}

type _Shared2d711327d8SubWorkflowParam Shared2d711327d8SubWorkflowParam

// NewShared2d711327d8SubWorkflowParam instantiates a new Shared2d711327d8SubWorkflowParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShared2d711327d8SubWorkflowParam(name string) *Shared2d711327d8SubWorkflowParam {
	this := Shared2d711327d8SubWorkflowParam{}
	this.Name = name
	return &this
}

// NewShared2d711327d8SubWorkflowParamWithDefaults instantiates a new Shared2d711327d8SubWorkflowParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShared2d711327d8SubWorkflowParamWithDefaults() *Shared2d711327d8SubWorkflowParam {
	this := Shared2d711327d8SubWorkflowParam{}
	return &this
}

// GetName returns the Name field value
func (o *Shared2d711327d8SubWorkflowParam) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Shared2d711327d8SubWorkflowParam) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Shared2d711327d8SubWorkflowParam) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *Shared2d711327d8SubWorkflowParam) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Shared2d711327d8SubWorkflowParam) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *Shared2d711327d8SubWorkflowParam) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *Shared2d711327d8SubWorkflowParam) SetVersion(v int32) {
	o.Version = &v
}

// GetTaskToDomain returns the TaskToDomain field value if set, zero value otherwise.
func (o *Shared2d711327d8SubWorkflowParam) GetTaskToDomain() map[string]string {
	if o == nil || IsNil(o.TaskToDomain) {
		var ret map[string]string
		return ret
	}
	return o.TaskToDomain
}

// GetTaskToDomainOk returns a tuple with the TaskToDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Shared2d711327d8SubWorkflowParam) GetTaskToDomainOk() (map[string]string, bool) {
	if o == nil || IsNil(o.TaskToDomain) {
		return map[string]string{}, false
	}
	return o.TaskToDomain, true
}

// HasTaskToDomain returns a boolean if a field has been set.
func (o *Shared2d711327d8SubWorkflowParam) HasTaskToDomain() bool {
	if o != nil && !IsNil(o.TaskToDomain) {
		return true
	}

	return false
}

// SetTaskToDomain gets a reference to the given map[string]string and assigns it to the TaskToDomain field.
func (o *Shared2d711327d8SubWorkflowParam) SetTaskToDomain(v map[string]string) {
	o.TaskToDomain = v
}

func (o Shared2d711327d8SubWorkflowParam) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Shared2d711327d8SubWorkflowParam) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.TaskToDomain) {
		toSerialize["taskToDomain"] = o.TaskToDomain
	}
	return toSerialize, nil
}

func (o *Shared2d711327d8SubWorkflowParam) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varShared2d711327d8SubWorkflowParam := _Shared2d711327d8SubWorkflowParam{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varShared2d711327d8SubWorkflowParam)

	if err != nil {
		return err
	}

	*o = Shared2d711327d8SubWorkflowParam(varShared2d711327d8SubWorkflowParam)

	return err
}

type NullableShared2d711327d8SubWorkflowParam struct {
	value *Shared2d711327d8SubWorkflowParam
	isSet bool
}

func (v NullableShared2d711327d8SubWorkflowParam) Get() *Shared2d711327d8SubWorkflowParam {
	return v.value
}

func (v *NullableShared2d711327d8SubWorkflowParam) Set(val *Shared2d711327d8SubWorkflowParam) {
	v.value = val
	v.isSet = true
}

func (v NullableShared2d711327d8SubWorkflowParam) IsSet() bool {
	return v.isSet
}

func (v *NullableShared2d711327d8SubWorkflowParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShared2d711327d8SubWorkflowParam(val *Shared2d711327d8SubWorkflowParam) *NullableShared2d711327d8SubWorkflowParam {
	return &NullableShared2d711327d8SubWorkflowParam{value: val, isSet: true}
}

func (v NullableShared2d711327d8SubWorkflowParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShared2d711327d8SubWorkflowParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


