/*
node-flow

Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nodeflow

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AuthCreateApiKeyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthCreateApiKeyRequest{}

// AuthCreateApiKeyRequest struct for AuthCreateApiKeyRequest
type AuthCreateApiKeyRequest struct {
	Name string `json:"name"`
	Scopes []string `json:"scopes,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

type _AuthCreateApiKeyRequest AuthCreateApiKeyRequest

// NewAuthCreateApiKeyRequest instantiates a new AuthCreateApiKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthCreateApiKeyRequest(name string) *AuthCreateApiKeyRequest {
	this := AuthCreateApiKeyRequest{}
	this.Name = name
	return &this
}

// NewAuthCreateApiKeyRequestWithDefaults instantiates a new AuthCreateApiKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthCreateApiKeyRequestWithDefaults() *AuthCreateApiKeyRequest {
	this := AuthCreateApiKeyRequest{}
	return &this
}

// GetName returns the Name field value
func (o *AuthCreateApiKeyRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AuthCreateApiKeyRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AuthCreateApiKeyRequest) SetName(v string) {
	o.Name = v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *AuthCreateApiKeyRequest) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthCreateApiKeyRequest) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *AuthCreateApiKeyRequest) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *AuthCreateApiKeyRequest) SetScopes(v []string) {
	o.Scopes = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *AuthCreateApiKeyRequest) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthCreateApiKeyRequest) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *AuthCreateApiKeyRequest) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *AuthCreateApiKeyRequest) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

func (o AuthCreateApiKeyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthCreateApiKeyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	return toSerialize, nil
}

func (o *AuthCreateApiKeyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthCreateApiKeyRequest := _AuthCreateApiKeyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthCreateApiKeyRequest)

	if err != nil {
		return err
	}

	*o = AuthCreateApiKeyRequest(varAuthCreateApiKeyRequest)

	return err
}

type NullableAuthCreateApiKeyRequest struct {
	value *AuthCreateApiKeyRequest
	isSet bool
}

func (v NullableAuthCreateApiKeyRequest) Get() *AuthCreateApiKeyRequest {
	return v.value
}

func (v *NullableAuthCreateApiKeyRequest) Set(val *AuthCreateApiKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthCreateApiKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthCreateApiKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthCreateApiKeyRequest(val *AuthCreateApiKeyRequest) *NullableAuthCreateApiKeyRequest {
	return &NullableAuthCreateApiKeyRequest{value: val, isSet: true}
}

func (v NullableAuthCreateApiKeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthCreateApiKeyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


