/*
node-flow

Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nodeflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MetadataImportBpmnDocumentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetadataImportBpmnDocumentRequest{}

// MetadataImportBpmnDocumentRequest struct for MetadataImportBpmnDocumentRequest
type MetadataImportBpmnDocumentRequest struct {
	Xml string `json:"xml"`
	ProcessId *string `json:"processId,omitempty"`
}

type _MetadataImportBpmnDocumentRequest MetadataImportBpmnDocumentRequest

// NewMetadataImportBpmnDocumentRequest instantiates a new MetadataImportBpmnDocumentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetadataImportBpmnDocumentRequest(xml string) *MetadataImportBpmnDocumentRequest {
	this := MetadataImportBpmnDocumentRequest{}
	this.Xml = xml
	return &this
}

// NewMetadataImportBpmnDocumentRequestWithDefaults instantiates a new MetadataImportBpmnDocumentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetadataImportBpmnDocumentRequestWithDefaults() *MetadataImportBpmnDocumentRequest {
	this := MetadataImportBpmnDocumentRequest{}
	return &this
}

// GetXml returns the Xml field value
func (o *MetadataImportBpmnDocumentRequest) GetXml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Xml
}

// GetXmlOk returns a tuple with the Xml field value
// and a boolean to check if the value has been set.
func (o *MetadataImportBpmnDocumentRequest) GetXmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Xml, true
}

// SetXml sets field value
func (o *MetadataImportBpmnDocumentRequest) SetXml(v string) {
	o.Xml = v
}

// GetProcessId returns the ProcessId field value if set, zero value otherwise.
func (o *MetadataImportBpmnDocumentRequest) GetProcessId() string {
	if o == nil || IsNil(o.ProcessId) {
		var ret string
		return ret
	}
	return *o.ProcessId
}

// GetProcessIdOk returns a tuple with the ProcessId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataImportBpmnDocumentRequest) GetProcessIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProcessId) {
		return nil, false
	}
	return o.ProcessId, true
}

// HasProcessId returns a boolean if a field has been set.
func (o *MetadataImportBpmnDocumentRequest) HasProcessId() bool {
	if o != nil && !IsNil(o.ProcessId) {
		return true
	}

	return false
}

// SetProcessId gets a reference to the given string and assigns it to the ProcessId field.
func (o *MetadataImportBpmnDocumentRequest) SetProcessId(v string) {
	o.ProcessId = &v
}

func (o MetadataImportBpmnDocumentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetadataImportBpmnDocumentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["xml"] = o.Xml
	if !IsNil(o.ProcessId) {
		toSerialize["processId"] = o.ProcessId
	}
	return toSerialize, nil
}

func (o *MetadataImportBpmnDocumentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"xml",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMetadataImportBpmnDocumentRequest := _MetadataImportBpmnDocumentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMetadataImportBpmnDocumentRequest)

	if err != nil {
		return err
	}

	*o = MetadataImportBpmnDocumentRequest(varMetadataImportBpmnDocumentRequest)

	return err
}

type NullableMetadataImportBpmnDocumentRequest struct {
	value *MetadataImportBpmnDocumentRequest
	isSet bool
}

func (v NullableMetadataImportBpmnDocumentRequest) Get() *MetadataImportBpmnDocumentRequest {
	return v.value
}

func (v *NullableMetadataImportBpmnDocumentRequest) Set(val *MetadataImportBpmnDocumentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMetadataImportBpmnDocumentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMetadataImportBpmnDocumentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetadataImportBpmnDocumentRequest(val *MetadataImportBpmnDocumentRequest) *NullableMetadataImportBpmnDocumentRequest {
	return &NullableMetadataImportBpmnDocumentRequest{value: val, isSet: true}
}

func (v NullableMetadataImportBpmnDocumentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetadataImportBpmnDocumentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


