/*
 * node-flow
 * Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.nodeflow.client.api;

import dev.nodeflow.client.ApiException;
import dev.nodeflow.client.model.ConductorStartWorkflowRequest;
import dev.nodeflow.client.model.ConductorTokenRequest;
import dev.nodeflow.client.model.ConductorUpdateTaskRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConductorApi
 */
@Disabled
public class ConductorApiTest {

    private final ConductorApi api = new ConductorApi();

    /**
     * Executions by correlation id (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorCorrelatedTest() throws ApiException {
        String name = null;
        String correlationId = null;
        Object response = api.conductorCorrelated(name, correlationId);
        // TODO: test validations
    }

    /**
     * Create task definitions (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorCreateTaskDefsTest() throws ApiException {
        Object response = api.conductorCreateTaskDefs();
        // TODO: test validations
    }

    /**
     * Delete a workflow version (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorDeleteWorkflowTest() throws ApiException {
        String name = null;
        String version = null;
        Object response = api.conductorDeleteWorkflow(name, version);
        // TODO: test validations
    }

    /**
     * Start a workflow and wait (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorExecuteWorkflowTest() throws ApiException {
        String name = null;
        Object response = api.conductorExecuteWorkflow(name);
        // TODO: test validations
    }

    /**
     * Start a workflow and wait (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorExecuteWorkflow2Test() throws ApiException {
        String name = null;
        String version = null;
        Object response = api.conductorExecuteWorkflow2(name, version);
        // TODO: test validations
    }

    /**
     * Fetch a task (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorGetTaskTest() throws ApiException {
        String taskId = null;
        Object response = api.conductorGetTask(taskId);
        // TODO: test validations
    }

    /**
     * Fetch a task definition (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorGetTaskDefTest() throws ApiException {
        String name = null;
        Object response = api.conductorGetTaskDef(name);
        // TODO: test validations
    }

    /**
     * Fetch a workflow definition (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorGetWorkflowTest() throws ApiException {
        String name = null;
        Object response = api.conductorGetWorkflow(name);
        // TODO: test validations
    }

    /**
     * Fetch an execution (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorGetWorkflowRunTest() throws ApiException {
        String workflowId = null;
        Object response = api.conductorGetWorkflowRun(workflowId);
        // TODO: test validations
    }

    /**
     * List task definitions (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorListTaskDefsTest() throws ApiException {
        Object response = api.conductorListTaskDefs();
        // TODO: test validations
    }

    /**
     * List workflow definitions (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorListWorkflowsTest() throws ApiException {
        Object response = api.conductorListWorkflows();
        // TODO: test validations
    }

    /**
     * Append a log line to a task (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorLogTest() throws ApiException {
        String taskId = null;
        Object response = api.conductorLog(taskId);
        // TODO: test validations
    }

    /**
     * Pause an execution (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorPauseTest() throws ApiException {
        String workflowId = null;
        Object response = api.conductorPause(workflowId);
        // TODO: test validations
    }

    /**
     * Poll for one task (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorPollTest() throws ApiException {
        String taskType = null;
        Object response = api.conductorPoll(taskType);
        // TODO: test validations
    }

    /**
     * Poll for a batch of tasks (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorPollBatchTest() throws ApiException {
        String taskType = null;
        Object response = api.conductorPollBatch(taskType);
        // TODO: test validations
    }

    /**
     * Queue depths by task type (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorQueueSizesTest() throws ApiException {
        Object response = api.conductorQueueSizes();
        // TODO: test validations
    }

    /**
     * Register a workflow definition (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorRegisterWorkflowTest() throws ApiException {
        Object response = api.conductorRegisterWorkflow();
        // TODO: test validations
    }

    /**
     * Register workflow definitions in bulk (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorRegisterWorkflowsTest() throws ApiException {
        Object response = api.conductorRegisterWorkflows();
        // TODO: test validations
    }

    /**
     * Re-run an execution from a task (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorRerunTest() throws ApiException {
        String workflowId = null;
        Object response = api.conductorRerun(workflowId);
        // TODO: test validations
    }

    /**
     * Restart an execution (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorRestartTest() throws ApiException {
        String workflowId = null;
        Object response = api.conductorRestart(workflowId);
        // TODO: test validations
    }

    /**
     * Resume an execution (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorResumeTest() throws ApiException {
        String workflowId = null;
        Object response = api.conductorResume(workflowId);
        // TODO: test validations
    }

    /**
     * Retry the failed tasks of an execution (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorRetryTest() throws ApiException {
        String workflowId = null;
        Object response = api.conductorRetry(workflowId);
        // TODO: test validations
    }

    /**
     * Search executions (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorSearchTest() throws ApiException {
        Object response = api.conductorSearch();
        // TODO: test validations
    }

    /**
     * Start a workflow by name (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorStartNamedTest() throws ApiException {
        String name = null;
        Object response = api.conductorStartNamed(name);
        // TODO: test validations
    }

    /**
     * Start a workflow (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorStartWorkflowTest() throws ApiException {
        ConductorStartWorkflowRequest conductorStartWorkflowRequest = null;
        Object response = api.conductorStartWorkflow(conductorStartWorkflowRequest);
        // TODO: test validations
    }

    /**
     * Terminate an execution (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorTerminateTest() throws ApiException {
        String workflowId = null;
        Object response = api.conductorTerminate(workflowId);
        // TODO: test validations
    }

    /**
     * Conductor-compatible token exchange
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorTokenTest() throws ApiException {
        ConductorTokenRequest conductorTokenRequest = null;
        Object response = api.conductorToken(conductorTokenRequest);
        // TODO: test validations
    }

    /**
     * Report a task result by reference (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorUpdateByRefTest() throws ApiException {
        String workflowId = null;
        String taskRefName = null;
        String status = null;
        Object response = api.conductorUpdateByRef(workflowId, taskRefName, status);
        // TODO: test validations
    }

    /**
     * Report a task result (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorUpdateTaskTest() throws ApiException {
        ConductorUpdateTaskRequest conductorUpdateTaskRequest = null;
        Object response = api.conductorUpdateTask(conductorUpdateTaskRequest);
        // TODO: test validations
    }

    /**
     * Update a task definition (Conductor)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conductorUpdateTaskDefTest() throws ApiException {
        Object response = api.conductorUpdateTaskDef();
        // TODO: test validations
    }

}
