/*
 * node-flow
 * Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.nodeflow.client.api;

import dev.nodeflow.client.ApiCallback;
import dev.nodeflow.client.ApiClient;
import dev.nodeflow.client.ApiException;
import dev.nodeflow.client.ApiResponse;
import dev.nodeflow.client.Configuration;
import dev.nodeflow.client.Pair;
import dev.nodeflow.client.ProgressRequestBody;
import dev.nodeflow.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import dev.nodeflow.client.model.EventHandlerTestRequest;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class EventsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public EventsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public EventsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for eventHandlerActivity
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param hours  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerActivityCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nullable Integer hours, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/event-handlers/activity"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (hours != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("hours", hours));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call eventHandlerActivityValidateBeforeCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nullable Integer hours, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling eventHandlerActivity(Async)");
        }

        return eventHandlerActivityCall(ns, hours, _callback);

    }

    /**
     * Event handler activity
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param hours  (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object eventHandlerActivity(@javax.annotation.Nonnull String ns, @javax.annotation.Nullable Integer hours) throws ApiException {
        ApiResponse<Object> localVarResp = eventHandlerActivityWithHttpInfo(ns, hours);
        return localVarResp.getData();
    }

    /**
     * Event handler activity
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param hours  (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> eventHandlerActivityWithHttpInfo(@javax.annotation.Nonnull String ns, @javax.annotation.Nullable Integer hours) throws ApiException {
        okhttp3.Call localVarCall = eventHandlerActivityValidateBeforeCall(ns, hours, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Event handler activity (asynchronously)
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param hours  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerActivityAsync(@javax.annotation.Nonnull String ns, @javax.annotation.Nullable Integer hours, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = eventHandlerActivityValidateBeforeCall(ns, hours, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for eventHandlerCreate
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerCreateCall(@javax.annotation.Nonnull String ns, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/event-handlers"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call eventHandlerCreateValidateBeforeCall(@javax.annotation.Nonnull String ns, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling eventHandlerCreate(Async)");
        }

        return eventHandlerCreateCall(ns, _callback);

    }

    /**
     * Create an inbound event handler
     * Maps a message on a configured source and topic to starting a workflow or finishing a task that is waiting for one.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object eventHandlerCreate(@javax.annotation.Nonnull String ns) throws ApiException {
        ApiResponse<Object> localVarResp = eventHandlerCreateWithHttpInfo(ns);
        return localVarResp.getData();
    }

    /**
     * Create an inbound event handler
     * Maps a message on a configured source and topic to starting a workflow or finishing a task that is waiting for one.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> eventHandlerCreateWithHttpInfo(@javax.annotation.Nonnull String ns) throws ApiException {
        okhttp3.Call localVarCall = eventHandlerCreateValidateBeforeCall(ns, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create an inbound event handler (asynchronously)
     * Maps a message on a configured source and topic to starting a workflow or finishing a task that is waiting for one.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerCreateAsync(@javax.annotation.Nonnull String ns, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = eventHandlerCreateValidateBeforeCall(ns, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for eventHandlerDisable
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerDisableCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/event-handlers/{name}/disable"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()))
            .replace("{" + "name" + "}", localVarApiClient.escapeString(name.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call eventHandlerDisableValidateBeforeCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling eventHandlerDisable(Async)");
        }

        // verify the required parameter 'name' is set
        if (name == null) {
            throw new ApiException("Missing the required parameter 'name' when calling eventHandlerDisable(Async)");
        }

        return eventHandlerDisableCall(ns, name, _callback);

    }

    /**
     * Disable an event handler
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object eventHandlerDisable(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name) throws ApiException {
        ApiResponse<Object> localVarResp = eventHandlerDisableWithHttpInfo(ns, name);
        return localVarResp.getData();
    }

    /**
     * Disable an event handler
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> eventHandlerDisableWithHttpInfo(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name) throws ApiException {
        okhttp3.Call localVarCall = eventHandlerDisableValidateBeforeCall(ns, name, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Disable an event handler (asynchronously)
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerDisableAsync(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = eventHandlerDisableValidateBeforeCall(ns, name, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for eventHandlerEnable
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerEnableCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/event-handlers/{name}/enable"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()))
            .replace("{" + "name" + "}", localVarApiClient.escapeString(name.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call eventHandlerEnableValidateBeforeCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling eventHandlerEnable(Async)");
        }

        // verify the required parameter 'name' is set
        if (name == null) {
            throw new ApiException("Missing the required parameter 'name' when calling eventHandlerEnable(Async)");
        }

        return eventHandlerEnableCall(ns, name, _callback);

    }

    /**
     * Enable an event handler
     * Takes effect on the consumer’s next start, since a newly-handled topic may need subscribing to.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object eventHandlerEnable(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name) throws ApiException {
        ApiResponse<Object> localVarResp = eventHandlerEnableWithHttpInfo(ns, name);
        return localVarResp.getData();
    }

    /**
     * Enable an event handler
     * Takes effect on the consumer’s next start, since a newly-handled topic may need subscribing to.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> eventHandlerEnableWithHttpInfo(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name) throws ApiException {
        okhttp3.Call localVarCall = eventHandlerEnableValidateBeforeCall(ns, name, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Enable an event handler (asynchronously)
     * Takes effect on the consumer’s next start, since a newly-handled topic may need subscribing to.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerEnableAsync(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = eventHandlerEnableValidateBeforeCall(ns, name, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for eventHandlerExecutions
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param handler  (optional)
     * @param outcome  (optional)
     * @param before  (optional)
     * @param limit  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerExecutionsCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nullable String handler, @javax.annotation.Nullable String outcome, @javax.annotation.Nullable UUID before, @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/event-handlers/executions"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (handler != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("handler", handler));
        }

        if (outcome != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("outcome", outcome));
        }

        if (before != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("before", before));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call eventHandlerExecutionsValidateBeforeCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nullable String handler, @javax.annotation.Nullable String outcome, @javax.annotation.Nullable UUID before, @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling eventHandlerExecutions(Async)");
        }

        return eventHandlerExecutionsCall(ns, handler, outcome, before, limit, _callback);

    }

    /**
     * Event executions — the event monitor
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param handler  (optional)
     * @param outcome  (optional)
     * @param before  (optional)
     * @param limit  (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object eventHandlerExecutions(@javax.annotation.Nonnull String ns, @javax.annotation.Nullable String handler, @javax.annotation.Nullable String outcome, @javax.annotation.Nullable UUID before, @javax.annotation.Nullable Integer limit) throws ApiException {
        ApiResponse<Object> localVarResp = eventHandlerExecutionsWithHttpInfo(ns, handler, outcome, before, limit);
        return localVarResp.getData();
    }

    /**
     * Event executions — the event monitor
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param handler  (optional)
     * @param outcome  (optional)
     * @param before  (optional)
     * @param limit  (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> eventHandlerExecutionsWithHttpInfo(@javax.annotation.Nonnull String ns, @javax.annotation.Nullable String handler, @javax.annotation.Nullable String outcome, @javax.annotation.Nullable UUID before, @javax.annotation.Nullable Integer limit) throws ApiException {
        okhttp3.Call localVarCall = eventHandlerExecutionsValidateBeforeCall(ns, handler, outcome, before, limit, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Event executions — the event monitor (asynchronously)
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param handler  (optional)
     * @param outcome  (optional)
     * @param before  (optional)
     * @param limit  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerExecutionsAsync(@javax.annotation.Nonnull String ns, @javax.annotation.Nullable String handler, @javax.annotation.Nullable String outcome, @javax.annotation.Nullable UUID before, @javax.annotation.Nullable Integer limit, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = eventHandlerExecutionsValidateBeforeCall(ns, handler, outcome, before, limit, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for eventHandlerGet
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerGetCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/event-handlers/{name}"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()))
            .replace("{" + "name" + "}", localVarApiClient.escapeString(name.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call eventHandlerGetValidateBeforeCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling eventHandlerGet(Async)");
        }

        // verify the required parameter 'name' is set
        if (name == null) {
            throw new ApiException("Missing the required parameter 'name' when calling eventHandlerGet(Async)");
        }

        return eventHandlerGetCall(ns, name, _callback);

    }

    /**
     * Fetch one event handler
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object eventHandlerGet(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name) throws ApiException {
        ApiResponse<Object> localVarResp = eventHandlerGetWithHttpInfo(ns, name);
        return localVarResp.getData();
    }

    /**
     * Fetch one event handler
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> eventHandlerGetWithHttpInfo(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name) throws ApiException {
        okhttp3.Call localVarCall = eventHandlerGetValidateBeforeCall(ns, name, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Fetch one event handler (asynchronously)
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerGetAsync(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = eventHandlerGetValidateBeforeCall(ns, name, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for eventHandlerList
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerListCall(@javax.annotation.Nonnull String ns, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/event-handlers"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call eventHandlerListValidateBeforeCall(@javax.annotation.Nonnull String ns, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling eventHandlerList(Async)");
        }

        return eventHandlerListCall(ns, _callback);

    }

    /**
     * List event handlers
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object eventHandlerList(@javax.annotation.Nonnull String ns) throws ApiException {
        ApiResponse<Object> localVarResp = eventHandlerListWithHttpInfo(ns);
        return localVarResp.getData();
    }

    /**
     * List event handlers
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> eventHandlerListWithHttpInfo(@javax.annotation.Nonnull String ns) throws ApiException {
        okhttp3.Call localVarCall = eventHandlerListValidateBeforeCall(ns, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List event handlers (asynchronously)
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerListAsync(@javax.annotation.Nonnull String ns, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = eventHandlerListValidateBeforeCall(ns, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for eventHandlerRemove
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerRemoveCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/event-handlers/{name}"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()))
            .replace("{" + "name" + "}", localVarApiClient.escapeString(name.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call eventHandlerRemoveValidateBeforeCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling eventHandlerRemove(Async)");
        }

        // verify the required parameter 'name' is set
        if (name == null) {
            throw new ApiException("Missing the required parameter 'name' when calling eventHandlerRemove(Async)");
        }

        return eventHandlerRemoveCall(ns, name, _callback);

    }

    /**
     * Delete an event handler
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public void eventHandlerRemove(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name) throws ApiException {
        eventHandlerRemoveWithHttpInfo(ns, name);
    }

    /**
     * Delete an event handler
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> eventHandlerRemoveWithHttpInfo(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name) throws ApiException {
        okhttp3.Call localVarCall = eventHandlerRemoveValidateBeforeCall(ns, name, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete an event handler (asynchronously)
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerRemoveAsync(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = eventHandlerRemoveValidateBeforeCall(ns, name, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for eventHandlerSources
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerSourcesCall(@javax.annotation.Nonnull String ns, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/event-handlers/sources"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call eventHandlerSourcesValidateBeforeCall(@javax.annotation.Nonnull String ns, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling eventHandlerSources(Async)");
        }

        return eventHandlerSourcesCall(ns, _callback);

    }

    /**
     * List configured event sources
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object eventHandlerSources(@javax.annotation.Nonnull String ns) throws ApiException {
        ApiResponse<Object> localVarResp = eventHandlerSourcesWithHttpInfo(ns);
        return localVarResp.getData();
    }

    /**
     * List configured event sources
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> eventHandlerSourcesWithHttpInfo(@javax.annotation.Nonnull String ns) throws ApiException {
        okhttp3.Call localVarCall = eventHandlerSourcesValidateBeforeCall(ns, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List configured event sources (asynchronously)
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerSourcesAsync(@javax.annotation.Nonnull String ns, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = eventHandlerSourcesValidateBeforeCall(ns, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for eventHandlerTest
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @param eventHandlerTestRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerTestCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, @javax.annotation.Nonnull EventHandlerTestRequest eventHandlerTestRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = eventHandlerTestRequest;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/event-handlers/{name}/test"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()))
            .replace("{" + "name" + "}", localVarApiClient.escapeString(name.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call eventHandlerTestValidateBeforeCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, @javax.annotation.Nonnull EventHandlerTestRequest eventHandlerTestRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling eventHandlerTest(Async)");
        }

        // verify the required parameter 'name' is set
        if (name == null) {
            throw new ApiException("Missing the required parameter 'name' when calling eventHandlerTest(Async)");
        }

        // verify the required parameter 'eventHandlerTestRequest' is set
        if (eventHandlerTestRequest == null) {
            throw new ApiException("Missing the required parameter 'eventHandlerTestRequest' when calling eventHandlerTest(Async)");
        }

        return eventHandlerTestCall(ns, name, eventHandlerTestRequest, _callback);

    }

    /**
     * Send a test message to an event handler
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @param eventHandlerTestRequest  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object eventHandlerTest(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, @javax.annotation.Nonnull EventHandlerTestRequest eventHandlerTestRequest) throws ApiException {
        ApiResponse<Object> localVarResp = eventHandlerTestWithHttpInfo(ns, name, eventHandlerTestRequest);
        return localVarResp.getData();
    }

    /**
     * Send a test message to an event handler
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @param eventHandlerTestRequest  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> eventHandlerTestWithHttpInfo(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, @javax.annotation.Nonnull EventHandlerTestRequest eventHandlerTestRequest) throws ApiException {
        okhttp3.Call localVarCall = eventHandlerTestValidateBeforeCall(ns, name, eventHandlerTestRequest, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Send a test message to an event handler (asynchronously)
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @param eventHandlerTestRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerTestAsync(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, @javax.annotation.Nonnull EventHandlerTestRequest eventHandlerTestRequest, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = eventHandlerTestValidateBeforeCall(ns, name, eventHandlerTestRequest, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for eventHandlerUpdate
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerUpdateCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/event-handlers/{name}"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()))
            .replace("{" + "name" + "}", localVarApiClient.escapeString(name.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call eventHandlerUpdateValidateBeforeCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling eventHandlerUpdate(Async)");
        }

        // verify the required parameter 'name' is set
        if (name == null) {
            throw new ApiException("Missing the required parameter 'name' when calling eventHandlerUpdate(Async)");
        }

        return eventHandlerUpdateCall(ns, name, _callback);

    }

    /**
     * Update an event handler
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object eventHandlerUpdate(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name) throws ApiException {
        ApiResponse<Object> localVarResp = eventHandlerUpdateWithHttpInfo(ns, name);
        return localVarResp.getData();
    }

    /**
     * Update an event handler
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> eventHandlerUpdateWithHttpInfo(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name) throws ApiException {
        okhttp3.Call localVarCall = eventHandlerUpdateValidateBeforeCall(ns, name, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update an event handler (asynchronously)
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param name  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call eventHandlerUpdateAsync(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String name, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = eventHandlerUpdateValidateBeforeCall(ns, name, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
