/*
 * node-flow
 * Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.nodeflow.client.api;

import dev.nodeflow.client.ApiCallback;
import dev.nodeflow.client.ApiClient;
import dev.nodeflow.client.ApiException;
import dev.nodeflow.client.ApiResponse;
import dev.nodeflow.client.Configuration;
import dev.nodeflow.client.Pair;
import dev.nodeflow.client.ProgressRequestBody;
import dev.nodeflow.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;



import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class HumanTasksApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public HumanTasksApi() {
        this(Configuration.getDefaultApiClient());
    }

    public HumanTasksApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for humanTaskClaim
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call humanTaskClaimCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/human-tasks/{id}/claim"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call humanTaskClaimValidateBeforeCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling humanTaskClaim(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling humanTaskClaim(Async)");
        }

        return humanTaskClaimCall(ns, id, _callback);

    }

    /**
     * Take possession of a human task
     * Single-winner: two people claiming the same task at the same moment resolve to one, and the loser is told rather than both starting work.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object humanTaskClaim(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<Object> localVarResp = humanTaskClaimWithHttpInfo(ns, id);
        return localVarResp.getData();
    }

    /**
     * Take possession of a human task
     * Single-winner: two people claiming the same task at the same moment resolve to one, and the loser is told rather than both starting work.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> humanTaskClaimWithHttpInfo(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = humanTaskClaimValidateBeforeCall(ns, id, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Take possession of a human task (asynchronously)
     * Single-winner: two people claiming the same task at the same moment resolve to one, and the loser is told rather than both starting work.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call humanTaskClaimAsync(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = humanTaskClaimValidateBeforeCall(ns, id, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for humanTaskComplete
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call humanTaskCompleteCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/human-tasks/{id}/complete"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call humanTaskCompleteValidateBeforeCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling humanTaskComplete(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling humanTaskComplete(Async)");
        }

        return humanTaskCompleteCall(ns, id, _callback);

    }

    /**
     * Complete a human task and let the workflow continue
     * Requires holding the claim. Without that, one person’s answer could silently replace another’s on a task they were actively working.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object humanTaskComplete(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<Object> localVarResp = humanTaskCompleteWithHttpInfo(ns, id);
        return localVarResp.getData();
    }

    /**
     * Complete a human task and let the workflow continue
     * Requires holding the claim. Without that, one person’s answer could silently replace another’s on a task they were actively working.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> humanTaskCompleteWithHttpInfo(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = humanTaskCompleteValidateBeforeCall(ns, id, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Complete a human task and let the workflow continue (asynchronously)
     * Requires holding the claim. Without that, one person’s answer could silently replace another’s on a task they were actively working.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call humanTaskCompleteAsync(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = humanTaskCompleteValidateBeforeCall(ns, id, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for humanTaskGet
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call humanTaskGetCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/human-tasks/{id}"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call humanTaskGetValidateBeforeCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling humanTaskGet(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling humanTaskGet(Async)");
        }

        return humanTaskGetCall(ns, id, _callback);

    }

    /**
     * Fetch one human task
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object humanTaskGet(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<Object> localVarResp = humanTaskGetWithHttpInfo(ns, id);
        return localVarResp.getData();
    }

    /**
     * Fetch one human task
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> humanTaskGetWithHttpInfo(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = humanTaskGetValidateBeforeCall(ns, id, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Fetch one human task (asynchronously)
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call humanTaskGetAsync(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = humanTaskGetValidateBeforeCall(ns, id, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for humanTaskInbox
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call humanTaskInboxCall(@javax.annotation.Nonnull String ns, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/human-tasks"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call humanTaskInboxValidateBeforeCall(@javax.annotation.Nonnull String ns, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling humanTaskInbox(Async)");
        }

        return humanTaskInboxCall(ns, _callback);

    }

    /**
     * List the human tasks this user can act on
     * Assigned to them, held by them, or unassigned and free to claim. Never another person&#39;s assignment, and never something someone else holds.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object humanTaskInbox(@javax.annotation.Nonnull String ns) throws ApiException {
        ApiResponse<Object> localVarResp = humanTaskInboxWithHttpInfo(ns);
        return localVarResp.getData();
    }

    /**
     * List the human tasks this user can act on
     * Assigned to them, held by them, or unassigned and free to claim. Never another person&#39;s assignment, and never something someone else holds.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> humanTaskInboxWithHttpInfo(@javax.annotation.Nonnull String ns) throws ApiException {
        okhttp3.Call localVarCall = humanTaskInboxValidateBeforeCall(ns, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List the human tasks this user can act on (asynchronously)
     * Assigned to them, held by them, or unassigned and free to claim. Never another person&#39;s assignment, and never something someone else holds.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call humanTaskInboxAsync(@javax.annotation.Nonnull String ns, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = humanTaskInboxValidateBeforeCall(ns, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for humanTaskReassign
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call humanTaskReassignCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/human-tasks/{id}/reassign"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call humanTaskReassignValidateBeforeCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling humanTaskReassign(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling humanTaskReassign(Async)");
        }

        return humanTaskReassignCall(ns, id, _callback);

    }

    /**
     * Replace who a human task is assigned to
     * An operator action. Takes an assignment chain — &#x60;[{ \&quot;user\&quot;: \&quot;email\&quot;, \&quot;slaMinutes\&quot;: 30 }, { \&quot;group\&quot;: \&quot;name\&quot; }]&#x60; — and releases any claim, so nobody keeps working a task that was moved away from them.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object humanTaskReassign(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<Object> localVarResp = humanTaskReassignWithHttpInfo(ns, id);
        return localVarResp.getData();
    }

    /**
     * Replace who a human task is assigned to
     * An operator action. Takes an assignment chain — &#x60;[{ \&quot;user\&quot;: \&quot;email\&quot;, \&quot;slaMinutes\&quot;: 30 }, { \&quot;group\&quot;: \&quot;name\&quot; }]&#x60; — and releases any claim, so nobody keeps working a task that was moved away from them.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> humanTaskReassignWithHttpInfo(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = humanTaskReassignValidateBeforeCall(ns, id, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Replace who a human task is assigned to (asynchronously)
     * An operator action. Takes an assignment chain — &#x60;[{ \&quot;user\&quot;: \&quot;email\&quot;, \&quot;slaMinutes\&quot;: 30 }, { \&quot;group\&quot;: \&quot;name\&quot; }]&#x60; — and releases any claim, so nobody keeps working a task that was moved away from them.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call humanTaskReassignAsync(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = humanTaskReassignValidateBeforeCall(ns, id, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for humanTaskRelease
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call humanTaskReleaseCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/human-tasks/{id}/release"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call humanTaskReleaseValidateBeforeCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling humanTaskRelease(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling humanTaskRelease(Async)");
        }

        return humanTaskReleaseCall(ns, id, _callback);

    }

    /**
     * Give a claimed task back to the pool
     * The assignment is left intact — releasing is not reassigning.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object humanTaskRelease(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<Object> localVarResp = humanTaskReleaseWithHttpInfo(ns, id);
        return localVarResp.getData();
    }

    /**
     * Give a claimed task back to the pool
     * The assignment is left intact — releasing is not reassigning.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> humanTaskReleaseWithHttpInfo(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = humanTaskReleaseValidateBeforeCall(ns, id, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Give a claimed task back to the pool (asynchronously)
     * The assignment is left intact — releasing is not reassigning.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call humanTaskReleaseAsync(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = humanTaskReleaseValidateBeforeCall(ns, id, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for humanTaskSearch
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call humanTaskSearchCall(@javax.annotation.Nonnull String ns, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/human-tasks/search"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call humanTaskSearchValidateBeforeCall(@javax.annotation.Nonnull String ns, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling humanTaskSearch(Async)");
        }

        return humanTaskSearchCall(ns, _callback);

    }

    /**
     * Search every human task in the namespace
     * The operator view: what is waiting, with whom, and for how long — across assignees, unlike the inbox. &#x60;state&#x60; is open (default), unclaimed, claimed, completed or all; &#x60;assignee&#x60; is an email, &#x60;group&#x60; a group name. Tasks of workflows the caller’s tags cannot reach are left out.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object humanTaskSearch(@javax.annotation.Nonnull String ns) throws ApiException {
        ApiResponse<Object> localVarResp = humanTaskSearchWithHttpInfo(ns);
        return localVarResp.getData();
    }

    /**
     * Search every human task in the namespace
     * The operator view: what is waiting, with whom, and for how long — across assignees, unlike the inbox. &#x60;state&#x60; is open (default), unclaimed, claimed, completed or all; &#x60;assignee&#x60; is an email, &#x60;group&#x60; a group name. Tasks of workflows the caller’s tags cannot reach are left out.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> humanTaskSearchWithHttpInfo(@javax.annotation.Nonnull String ns) throws ApiException {
        okhttp3.Call localVarCall = humanTaskSearchValidateBeforeCall(ns, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Search every human task in the namespace (asynchronously)
     * The operator view: what is waiting, with whom, and for how long — across assignees, unlike the inbox. &#x60;state&#x60; is open (default), unclaimed, claimed, completed or all; &#x60;assignee&#x60; is an email, &#x60;group&#x60; a group name. Tasks of workflows the caller’s tags cannot reach are left out.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call humanTaskSearchAsync(@javax.annotation.Nonnull String ns, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = humanTaskSearchValidateBeforeCall(ns, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for humanTaskSkip
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call humanTaskSkipCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/human-tasks/{id}/skip"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call humanTaskSkipValidateBeforeCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling humanTaskSkip(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling humanTaskSkip(Async)");
        }

        return humanTaskSkipCall(ns, id, _callback);

    }

    /**
     * Skip a human task
     * The workflow continues as if the task completed; the reason is recorded in its output.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object humanTaskSkip(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<Object> localVarResp = humanTaskSkipWithHttpInfo(ns, id);
        return localVarResp.getData();
    }

    /**
     * Skip a human task
     * The workflow continues as if the task completed; the reason is recorded in its output.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> humanTaskSkipWithHttpInfo(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = humanTaskSkipValidateBeforeCall(ns, id, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Skip a human task (asynchronously)
     * The workflow continues as if the task completed; the reason is recorded in its output.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call humanTaskSkipAsync(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = humanTaskSkipValidateBeforeCall(ns, id, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
