/*
 * node-flow
 * Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.nodeflow.client.api;

import dev.nodeflow.client.ApiCallback;
import dev.nodeflow.client.ApiClient;
import dev.nodeflow.client.ApiException;
import dev.nodeflow.client.ApiResponse;
import dev.nodeflow.client.Configuration;
import dev.nodeflow.client.Pair;
import dev.nodeflow.client.ProgressRequestBody;
import dev.nodeflow.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import dev.nodeflow.client.model.PermissionsPutRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PermissionsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public PermissionsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PermissionsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for permissionsList
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call permissionsListCall(@javax.annotation.Nonnull String ns, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/permissions"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call permissionsListValidateBeforeCall(@javax.annotation.Nonnull String ns, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling permissionsList(Async)");
        }

        return permissionsListCall(ns, _callback);

    }

    /**
     * List resource grants, for one resource or one subject
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object permissionsList(@javax.annotation.Nonnull String ns) throws ApiException {
        ApiResponse<Object> localVarResp = permissionsListWithHttpInfo(ns);
        return localVarResp.getData();
    }

    /**
     * List resource grants, for one resource or one subject
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> permissionsListWithHttpInfo(@javax.annotation.Nonnull String ns) throws ApiException {
        okhttp3.Call localVarCall = permissionsListValidateBeforeCall(ns, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List resource grants, for one resource or one subject (asynchronously)
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call permissionsListAsync(@javax.annotation.Nonnull String ns, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = permissionsListValidateBeforeCall(ns, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for permissionsPut
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param permissionsPutRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call permissionsPutCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull PermissionsPutRequest permissionsPutRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = permissionsPutRequest;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/permissions"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call permissionsPutValidateBeforeCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull PermissionsPutRequest permissionsPutRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling permissionsPut(Async)");
        }

        // verify the required parameter 'permissionsPutRequest' is set
        if (permissionsPutRequest == null) {
            throw new ApiException("Missing the required parameter 'permissionsPutRequest' when calling permissionsPut(Async)");
        }

        return permissionsPutCall(ns, permissionsPutRequest, _callback);

    }

    /**
     * Grant a user, group or application access to a resource
     * Replaces that subject’s access to that target. &#x60;resource&#x60; is a name, a prefix ending in &#x60;*&#x60;, &#x60;tag:key:value&#x60;, &#x60;tag:key:*&#x60; or &#x60;*&#x60;. Any access implies READ. An empty &#x60;access&#x60; list removes the grant.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param permissionsPutRequest  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public Object permissionsPut(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull PermissionsPutRequest permissionsPutRequest) throws ApiException {
        ApiResponse<Object> localVarResp = permissionsPutWithHttpInfo(ns, permissionsPutRequest);
        return localVarResp.getData();
    }

    /**
     * Grant a user, group or application access to a resource
     * Replaces that subject’s access to that target. &#x60;resource&#x60; is a name, a prefix ending in &#x60;*&#x60;, &#x60;tag:key:value&#x60;, &#x60;tag:key:*&#x60; or &#x60;*&#x60;. Any access implies READ. An empty &#x60;access&#x60; list removes the grant.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param permissionsPutRequest  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> permissionsPutWithHttpInfo(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull PermissionsPutRequest permissionsPutRequest) throws ApiException {
        okhttp3.Call localVarCall = permissionsPutValidateBeforeCall(ns, permissionsPutRequest, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Grant a user, group or application access to a resource (asynchronously)
     * Replaces that subject’s access to that target. &#x60;resource&#x60; is a name, a prefix ending in &#x60;*&#x60;, &#x60;tag:key:value&#x60;, &#x60;tag:key:*&#x60; or &#x60;*&#x60;. Any access implies READ. An empty &#x60;access&#x60; list removes the grant.
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param permissionsPutRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call permissionsPutAsync(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull PermissionsPutRequest permissionsPutRequest, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = permissionsPutValidateBeforeCall(ns, permissionsPutRequest, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for permissionsRemove
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call permissionsRemoveCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/ns/{ns}/permissions/{id}"
            .replace("{" + "ns" + "}", localVarApiClient.escapeString(ns.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey", "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call permissionsRemoveValidateBeforeCall(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ns' is set
        if (ns == null) {
            throw new ApiException("Missing the required parameter 'ns' when calling permissionsRemove(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling permissionsRemove(Async)");
        }

        return permissionsRemoveCall(ns, id, _callback);

    }

    /**
     * Remove a resource grant
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public void permissionsRemove(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id) throws ApiException {
        permissionsRemoveWithHttpInfo(ns, id);
    }

    /**
     * Remove a resource grant
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> permissionsRemoveWithHttpInfo(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = permissionsRemoveValidateBeforeCall(ns, id, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Remove a resource grant (asynchronously)
     * 
     * @param ns Namespace slug. Must match the namespace of the credential, or the request is refused — it does not select one. (required)
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> No or invalid credentials </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated, but missing a required scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call permissionsRemoveAsync(@javax.annotation.Nonnull String ns, @javax.annotation.Nonnull String id, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = permissionsRemoveValidateBeforeCall(ns, id, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
