# coding: utf-8

"""
    node-flow

    Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from node_flow_client.models.status_listener_create_request_config_any_of import StatusListenerCreateRequestConfigAnyOf

class TestStatusListenerCreateRequestConfigAnyOf(unittest.TestCase):
    """StatusListenerCreateRequestConfigAnyOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatusListenerCreateRequestConfigAnyOf:
        """Test StatusListenerCreateRequestConfigAnyOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatusListenerCreateRequestConfigAnyOf`
        """
        model = StatusListenerCreateRequestConfigAnyOf()
        if include_optional:
            return StatusListenerCreateRequestConfigAnyOf(
                url = '0',
                secret_name = '0',
                headers = {
                    'key' : ''
                    }
            )
        else:
            return StatusListenerCreateRequestConfigAnyOf(
                url = '0',
        )
        """

    def testStatusListenerCreateRequestConfigAnyOf(self):
        """Test StatusListenerCreateRequestConfigAnyOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
