# coding: utf-8

"""
    node-flow

    Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from node_flow_client.models.metadata_register_workflow_request_rate_limit_config import MetadataRegisterWorkflowRequestRateLimitConfig

class TestMetadataRegisterWorkflowRequestRateLimitConfig(unittest.TestCase):
    """MetadataRegisterWorkflowRequestRateLimitConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetadataRegisterWorkflowRequestRateLimitConfig:
        """Test MetadataRegisterWorkflowRequestRateLimitConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetadataRegisterWorkflowRequestRateLimitConfig`
        """
        model = MetadataRegisterWorkflowRequestRateLimitConfig()
        if include_optional:
            return MetadataRegisterWorkflowRequestRateLimitConfig(
                rate_limit_key = '0',
                concurrent_exec_limit = 1
            )
        else:
            return MetadataRegisterWorkflowRequestRateLimitConfig(
                rate_limit_key = '0',
                concurrent_exec_limit = 1,
        )
        """

    def testMetadataRegisterWorkflowRequestRateLimitConfig(self):
        """Test MetadataRegisterWorkflowRequestRateLimitConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
