# coding: utf-8

"""
    node-flow

    Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from node_flow_client.models.vector_index_search_request import VectorIndexSearchRequest

class TestVectorIndexSearchRequest(unittest.TestCase):
    """VectorIndexSearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VectorIndexSearchRequest:
        """Test VectorIndexSearchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VectorIndexSearchRequest`
        """
        model = VectorIndexSearchRequest()
        if include_optional:
            return VectorIndexSearchRequest(
                llm_provider = '0',
                embedding_model = '0',
                query = '0',
                top_k = 1,
                min_score = -1
            )
        else:
            return VectorIndexSearchRequest(
                llm_provider = '0',
                query = '0',
        )
        """

    def testVectorIndexSearchRequest(self):
        """Test VectorIndexSearchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
