# coding: utf-8

"""
    node-flow

    Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from node_flow_client.models.execution_search_executions_request import ExecutionSearchExecutionsRequest

class TestExecutionSearchExecutionsRequest(unittest.TestCase):
    """ExecutionSearchExecutionsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExecutionSearchExecutionsRequest:
        """Test ExecutionSearchExecutionsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExecutionSearchExecutionsRequest`
        """
        model = ExecutionSearchExecutionsRequest()
        if include_optional:
            return ExecutionSearchExecutionsRequest(
                status = [
                    'RUNNING'
                    ],
                def_name = '',
                def_version = 1,
                correlation_id = '',
                workflow_id = '',
                idempotency_key = '',
                exclude_sub_workflows = True,
                started_after = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                started_before = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                finished = True,
                limit = 1,
                cursor = '',
                q = ''
            )
        else:
            return ExecutionSearchExecutionsRequest(
        )
        """

    def testExecutionSearchExecutionsRequest(self):
        """Test ExecutionSearchExecutionsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
