# coding: utf-8

"""
    node-flow

    Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from node_flow_client.models.prompt_test_request import PromptTestRequest

class TestPromptTestRequest(unittest.TestCase):
    """PromptTestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromptTestRequest:
        """Test PromptTestRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromptTestRequest`
        """
        model = PromptTestRequest()
        if include_optional:
            return PromptTestRequest(
                llm_provider = '0',
                model = '0',
                temperature = 0,
                max_tokens = 1,
                template = '0',
                name = '0',
                version = 1,
                variables = {
                    'key' : null
                    },
                instructions = ''
            )
        else:
            return PromptTestRequest(
                llm_provider = '0',
        )
        """

    def testPromptTestRequest(self):
        """Test PromptTestRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
