/* tslint:disable */
/* eslint-disable */
/**
 * node-flow
 * Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecutionPushMessageRequest
 */
export interface ExecutionPushMessageRequest {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ExecutionPushMessageRequest
     */
    payload: { [key: string]: any; };
}

/**
 * Check if a given object implements the ExecutionPushMessageRequest interface.
 */
export function instanceOfExecutionPushMessageRequest(value: object): value is ExecutionPushMessageRequest {
    if (!('payload' in value) || value['payload'] === undefined) return false;
    return true;
}

export function ExecutionPushMessageRequestFromJSON(json: any): ExecutionPushMessageRequest {
    return ExecutionPushMessageRequestFromJSONTyped(json, false);
}

export function ExecutionPushMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecutionPushMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'payload': json['payload'],
    };
}

export function ExecutionPushMessageRequestToJSON(json: any): ExecutionPushMessageRequest {
    return ExecutionPushMessageRequestToJSONTyped(json, false);
}

export function ExecutionPushMessageRequestToJSONTyped(value?: ExecutionPushMessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payload': value['payload'],
    };
}

