/* tslint:disable */
/* eslint-disable */
/**
 * node-flow
 * Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PromptSaveRequest
 */
export interface PromptSaveRequest {
    /**
     * 
     * @type {string}
     * @memberof PromptSaveRequest
     */
    template: string;
    /**
     * 
     * @type {string}
     * @memberof PromptSaveRequest
     */
    description?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PromptSaveRequest
     */
    models?: Array<string>;
}

/**
 * Check if a given object implements the PromptSaveRequest interface.
 */
export function instanceOfPromptSaveRequest(value: object): value is PromptSaveRequest {
    if (!('template' in value) || value['template'] === undefined) return false;
    return true;
}

export function PromptSaveRequestFromJSON(json: any): PromptSaveRequest {
    return PromptSaveRequestFromJSONTyped(json, false);
}

export function PromptSaveRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromptSaveRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'template': json['template'],
        'description': json['description'] == null ? undefined : json['description'],
        'models': json['models'] == null ? undefined : json['models'],
    };
}

export function PromptSaveRequestToJSON(json: any): PromptSaveRequest {
    return PromptSaveRequestToJSONTyped(json, false);
}

export function PromptSaveRequestToJSONTyped(value?: PromptSaveRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'template': value['template'],
        'description': value['description'],
        'models': value['models'],
    };
}

