/* tslint:disable */
/* eslint-disable */
/**
 * node-flow
 * Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Shared2d711327d8SubWorkflowParam
 */
export interface Shared2d711327d8SubWorkflowParam {
    /**
     * 
     * @type {string}
     * @memberof Shared2d711327d8SubWorkflowParam
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Shared2d711327d8SubWorkflowParam
     */
    version?: number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Shared2d711327d8SubWorkflowParam
     */
    taskToDomain?: { [key: string]: string; };
}

/**
 * Check if a given object implements the Shared2d711327d8SubWorkflowParam interface.
 */
export function instanceOfShared2d711327d8SubWorkflowParam(value: object): value is Shared2d711327d8SubWorkflowParam {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function Shared2d711327d8SubWorkflowParamFromJSON(json: any): Shared2d711327d8SubWorkflowParam {
    return Shared2d711327d8SubWorkflowParamFromJSONTyped(json, false);
}

export function Shared2d711327d8SubWorkflowParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): Shared2d711327d8SubWorkflowParam {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'taskToDomain': json['taskToDomain'] == null ? undefined : json['taskToDomain'],
    };
}

export function Shared2d711327d8SubWorkflowParamToJSON(json: any): Shared2d711327d8SubWorkflowParam {
    return Shared2d711327d8SubWorkflowParamToJSONTyped(json, false);
}

export function Shared2d711327d8SubWorkflowParamToJSONTyped(value?: Shared2d711327d8SubWorkflowParam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'version': value['version'],
        'taskToDomain': value['taskToDomain'],
    };
}

