/* tslint:disable */
/* eslint-disable */
/**
 * node-flow
 * Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Shared2d711327d8CacheConfig
 */
export interface Shared2d711327d8CacheConfig {
    /**
     * 
     * @type {string}
     * @memberof Shared2d711327d8CacheConfig
     */
    key: string;
    /**
     * 
     * @type {number}
     * @memberof Shared2d711327d8CacheConfig
     */
    ttlInSecond: number;
}

/**
 * Check if a given object implements the Shared2d711327d8CacheConfig interface.
 */
export function instanceOfShared2d711327d8CacheConfig(value: object): value is Shared2d711327d8CacheConfig {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('ttlInSecond' in value) || value['ttlInSecond'] === undefined) return false;
    return true;
}

export function Shared2d711327d8CacheConfigFromJSON(json: any): Shared2d711327d8CacheConfig {
    return Shared2d711327d8CacheConfigFromJSONTyped(json, false);
}

export function Shared2d711327d8CacheConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): Shared2d711327d8CacheConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'ttlInSecond': json['ttlInSecond'],
    };
}

export function Shared2d711327d8CacheConfigToJSON(json: any): Shared2d711327d8CacheConfig {
    return Shared2d711327d8CacheConfigToJSONTyped(json, false);
}

export function Shared2d711327d8CacheConfigToJSONTyped(value?: Shared2d711327d8CacheConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'ttlInSecond': value['ttlInSecond'],
    };
}

