/* tslint:disable */
/* eslint-disable */
/**
 * node-flow
 * Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskAppendLogsRequestLogsInner
 */
export interface TaskAppendLogsRequestLogsInner {
    /**
     * 
     * @type {string}
     * @memberof TaskAppendLogsRequestLogsInner
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof TaskAppendLogsRequestLogsInner
     */
    level?: TaskAppendLogsRequestLogsInnerLevelEnum;
}


/**
 * @export
 */
export const TaskAppendLogsRequestLogsInnerLevelEnum = {
    Debug: 'debug',
    Info: 'info',
    Warn: 'warn',
    Error: 'error'
} as const;
export type TaskAppendLogsRequestLogsInnerLevelEnum = typeof TaskAppendLogsRequestLogsInnerLevelEnum[keyof typeof TaskAppendLogsRequestLogsInnerLevelEnum];


/**
 * Check if a given object implements the TaskAppendLogsRequestLogsInner interface.
 */
export function instanceOfTaskAppendLogsRequestLogsInner(value: object): value is TaskAppendLogsRequestLogsInner {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function TaskAppendLogsRequestLogsInnerFromJSON(json: any): TaskAppendLogsRequestLogsInner {
    return TaskAppendLogsRequestLogsInnerFromJSONTyped(json, false);
}

export function TaskAppendLogsRequestLogsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskAppendLogsRequestLogsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'level': json['level'] == null ? undefined : json['level'],
    };
}

export function TaskAppendLogsRequestLogsInnerToJSON(json: any): TaskAppendLogsRequestLogsInner {
    return TaskAppendLogsRequestLogsInnerToJSONTyped(json, false);
}

export function TaskAppendLogsRequestLogsInnerToJSONTyped(value?: TaskAppendLogsRequestLogsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'level': value['level'],
    };
}

