/*
 * node-flow
 * Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.nodeflow.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.nodeflow.client.model.IncomingWebhookCreateRequestConfig;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import dev.nodeflow.client.JSON;

/**
 * IncomingWebhookCreateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class IncomingWebhookCreateRequest {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  /**
   * Gets or Sets verifier
   */
  @JsonAdapter(VerifierEnum.Adapter.class)
  public enum VerifierEnum {
    GITHUB("GITHUB"),
    
    STRIPE("STRIPE"),
    
    SLACK("SLACK"),
    
    SHOPIFY("SHOPIFY"),
    
    HMAC("HMAC"),
    
    HEADER("HEADER"),
    
    NONE("NONE");

    private String value;

    VerifierEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static VerifierEnum fromValue(String value) {
      for (VerifierEnum b : VerifierEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<VerifierEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final VerifierEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public VerifierEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return VerifierEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      VerifierEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_VERIFIER = "verifier";
  @SerializedName(SERIALIZED_NAME_VERIFIER)
  @javax.annotation.Nonnull
  private VerifierEnum verifier;

  public static final String SERIALIZED_NAME_CONFIG = "config";
  @SerializedName(SERIALIZED_NAME_CONFIG)
  @javax.annotation.Nullable
  private IncomingWebhookCreateRequestConfig config;

  public static final String SERIALIZED_NAME_SECRET_NAME = "secretName";
  @SerializedName(SERIALIZED_NAME_SECRET_NAME)
  @javax.annotation.Nullable
  private String secretName;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  @javax.annotation.Nullable
  private Boolean enabled;

  public IncomingWebhookCreateRequest() {
  }

  public IncomingWebhookCreateRequest name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public IncomingWebhookCreateRequest description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public IncomingWebhookCreateRequest verifier(@javax.annotation.Nonnull VerifierEnum verifier) {
    this.verifier = verifier;
    return this;
  }

  /**
   * Get verifier
   * @return verifier
   */
  @javax.annotation.Nonnull
  public VerifierEnum getVerifier() {
    return verifier;
  }

  public void setVerifier(@javax.annotation.Nonnull VerifierEnum verifier) {
    this.verifier = verifier;
  }


  public IncomingWebhookCreateRequest config(@javax.annotation.Nullable IncomingWebhookCreateRequestConfig config) {
    this.config = config;
    return this;
  }

  /**
   * Get config
   * @return config
   */
  @javax.annotation.Nullable
  public IncomingWebhookCreateRequestConfig getConfig() {
    return config;
  }

  public void setConfig(@javax.annotation.Nullable IncomingWebhookCreateRequestConfig config) {
    this.config = config;
  }


  public IncomingWebhookCreateRequest secretName(@javax.annotation.Nullable String secretName) {
    this.secretName = secretName;
    return this;
  }

  /**
   * Get secretName
   * @return secretName
   */
  @javax.annotation.Nullable
  public String getSecretName() {
    return secretName;
  }

  public void setSecretName(@javax.annotation.Nullable String secretName) {
    this.secretName = secretName;
  }


  public IncomingWebhookCreateRequest enabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Get enabled
   * @return enabled
   */
  @javax.annotation.Nullable
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IncomingWebhookCreateRequest incomingWebhookCreateRequest = (IncomingWebhookCreateRequest) o;
    return Objects.equals(this.name, incomingWebhookCreateRequest.name) &&
        Objects.equals(this.description, incomingWebhookCreateRequest.description) &&
        Objects.equals(this.verifier, incomingWebhookCreateRequest.verifier) &&
        Objects.equals(this.config, incomingWebhookCreateRequest.config) &&
        Objects.equals(this.secretName, incomingWebhookCreateRequest.secretName) &&
        Objects.equals(this.enabled, incomingWebhookCreateRequest.enabled);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, verifier, config, secretName, enabled);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IncomingWebhookCreateRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    verifier: ").append(toIndentedString(verifier)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    secretName: ").append(toIndentedString(secretName)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "description", "verifier", "config", "secretName", "enabled"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("name", "verifier"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to IncomingWebhookCreateRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IncomingWebhookCreateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in IncomingWebhookCreateRequest is not found in the empty JSON string", IncomingWebhookCreateRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IncomingWebhookCreateRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `IncomingWebhookCreateRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : IncomingWebhookCreateRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if (!jsonObj.get("verifier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `verifier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("verifier").toString()));
      }
      // validate the required field `verifier`
      VerifierEnum.validateJsonElement(jsonObj.get("verifier"));
      // validate the optional field `config`
      if (jsonObj.get("config") != null && !jsonObj.get("config").isJsonNull()) {
        IncomingWebhookCreateRequestConfig.validateJsonElement(jsonObj.get("config"));
      }
      if ((jsonObj.get("secretName") != null && !jsonObj.get("secretName").isJsonNull()) && !jsonObj.get("secretName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `secretName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("secretName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IncomingWebhookCreateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IncomingWebhookCreateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IncomingWebhookCreateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IncomingWebhookCreateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<IncomingWebhookCreateRequest>() {
           @Override
           public void write(JsonWriter out, IncomingWebhookCreateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IncomingWebhookCreateRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of IncomingWebhookCreateRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of IncomingWebhookCreateRequest
   * @throws IOException if the JSON string is invalid with respect to IncomingWebhookCreateRequest
   */
  public static IncomingWebhookCreateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IncomingWebhookCreateRequest.class);
  }

  /**
   * Convert an instance of IncomingWebhookCreateRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

