/*
 * node-flow
 * Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.nodeflow.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import dev.nodeflow.client.JSON;

/**
 * Shared2d711327d8CacheConfig
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class Shared2d711327d8CacheConfig {
  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  @javax.annotation.Nonnull
  private String key;

  public static final String SERIALIZED_NAME_TTL_IN_SECOND = "ttlInSecond";
  @SerializedName(SERIALIZED_NAME_TTL_IN_SECOND)
  @javax.annotation.Nonnull
  private Integer ttlInSecond;

  public Shared2d711327d8CacheConfig() {
  }

  public Shared2d711327d8CacheConfig key(@javax.annotation.Nonnull String key) {
    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @javax.annotation.Nonnull
  public String getKey() {
    return key;
  }

  public void setKey(@javax.annotation.Nonnull String key) {
    this.key = key;
  }


  public Shared2d711327d8CacheConfig ttlInSecond(@javax.annotation.Nonnull Integer ttlInSecond) {
    this.ttlInSecond = ttlInSecond;
    return this;
  }

  /**
   * Get ttlInSecond
   * minimum: 1
   * maximum: 31536000
   * @return ttlInSecond
   */
  @javax.annotation.Nonnull
  public Integer getTtlInSecond() {
    return ttlInSecond;
  }

  public void setTtlInSecond(@javax.annotation.Nonnull Integer ttlInSecond) {
    this.ttlInSecond = ttlInSecond;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Shared2d711327d8CacheConfig shared2d711327d8CacheConfig = (Shared2d711327d8CacheConfig) o;
    return Objects.equals(this.key, shared2d711327d8CacheConfig.key) &&
        Objects.equals(this.ttlInSecond, shared2d711327d8CacheConfig.ttlInSecond);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, ttlInSecond);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Shared2d711327d8CacheConfig {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    ttlInSecond: ").append(toIndentedString(ttlInSecond)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("key", "ttlInSecond"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("key", "ttlInSecond"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Shared2d711327d8CacheConfig
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Shared2d711327d8CacheConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in Shared2d711327d8CacheConfig is not found in the empty JSON string", Shared2d711327d8CacheConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Shared2d711327d8CacheConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Shared2d711327d8CacheConfig` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Shared2d711327d8CacheConfig.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("key").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Shared2d711327d8CacheConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Shared2d711327d8CacheConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Shared2d711327d8CacheConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Shared2d711327d8CacheConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<Shared2d711327d8CacheConfig>() {
           @Override
           public void write(JsonWriter out, Shared2d711327d8CacheConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Shared2d711327d8CacheConfig read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Shared2d711327d8CacheConfig given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Shared2d711327d8CacheConfig
   * @throws IOException if the JSON string is invalid with respect to Shared2d711327d8CacheConfig
   */
  public static Shared2d711327d8CacheConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Shared2d711327d8CacheConfig.class);
  }

  /**
   * Convert an instance of Shared2d711327d8CacheConfig to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

