/*
 * node-flow
 * Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.nodeflow.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.nodeflow.client.model.Shared2d711327d8CacheConfig;
import dev.nodeflow.client.model.Shared2d711327d8CompensateWith;
import dev.nodeflow.client.model.Shared2d711327d8SubWorkflowParam;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import dev.nodeflow.client.JSON;

/**
 * Shared2d711327d8
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class Shared2d711327d8 {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_TASK_REFERENCE_NAME = "taskReferenceName";
  @SerializedName(SERIALIZED_NAME_TASK_REFERENCE_NAME)
  @javax.annotation.Nonnull
  private String taskReferenceName;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    SIMPLE("SIMPLE"),
    
    SWITCH("SWITCH"),
    
    DO_WHILE("DO_WHILE"),
    
    FORK_JOIN("FORK_JOIN"),
    
    FORK_JOIN_DYNAMIC("FORK_JOIN_DYNAMIC"),
    
    JOIN("JOIN"),
    
    EXCLUSIVE_JOIN("EXCLUSIVE_JOIN"),
    
    DYNAMIC("DYNAMIC"),
    
    SUB_WORKFLOW("SUB_WORKFLOW"),
    
    START_WORKFLOW("START_WORKFLOW"),
    
    TERMINATE("TERMINATE"),
    
    SET_VARIABLE("SET_VARIABLE"),
    
    GET_WORKFLOW("GET_WORKFLOW"),
    
    YIELD("YIELD"),
    
    NOOP("NOOP"),
    
    HTTP("HTTP"),
    
    HTTP_POLL("HTTP_POLL"),
    
    INLINE("INLINE"),
    
    JSON_JQ_TRANSFORM("JSON_JQ_TRANSFORM"),
    
    EVENT("EVENT"),
    
    KAFKA_PUBLISH("KAFKA_PUBLISH"),
    
    WAIT("WAIT"),
    
    WAIT_FOR_WEBHOOK("WAIT_FOR_WEBHOOK"),
    
    PULL_WORKFLOW_MESSAGES("PULL_WORKFLOW_MESSAGES"),
    
    WEBHOOK("WEBHOOK"),
    
    HUMAN("HUMAN"),
    
    BUSINESS_RULE("BUSINESS_RULE"),
    
    JDBC("JDBC"),
    
    GRPC("GRPC"),
    
    UPDATE_TASK("UPDATE_TASK"),
    
    UPDATE_SECRET("UPDATE_SECRET"),
    
    GET_SIGNED_JWT("GET_SIGNED_JWT"),
    
    LLM_TEXT_COMPLETE("LLM_TEXT_COMPLETE"),
    
    LLM_CHAT_COMPLETE("LLM_CHAT_COMPLETE"),
    
    LLM_GENERATE_EMBEDDINGS("LLM_GENERATE_EMBEDDINGS"),
    
    LLM_INDEX_TEXT("LLM_INDEX_TEXT"),
    
    LLM_SEARCH_INDEX("LLM_SEARCH_INDEX"),
    
    CHUNK_TEXT("CHUNK_TEXT"),
    
    LIST_MCP_TOOLS("LIST_MCP_TOOLS"),
    
    CALL_MCP_TOOL("CALL_MCP_TOOL"),
    
    AGENT("AGENT"),
    
    PARSE_DOCUMENT("PARSE_DOCUMENT"),
    
    GENERATE_IMAGE("GENERATE_IMAGE"),
    
    GENERATE_AUDIO("GENERATE_AUDIO"),
    
    GENERATE_VIDEO("GENERATE_VIDEO");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private TypeEnum type;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_INPUT_PARAMETERS = "inputParameters";
  @SerializedName(SERIALIZED_NAME_INPUT_PARAMETERS)
  @javax.annotation.Nullable
  private Map<String, Object> inputParameters = new HashMap<>();

  public static final String SERIALIZED_NAME_OPTIONAL = "optional";
  @SerializedName(SERIALIZED_NAME_OPTIONAL)
  @javax.annotation.Nullable
  private Boolean optional;

  public static final String SERIALIZED_NAME_ASYNC_COMPLETE = "asyncComplete";
  @SerializedName(SERIALIZED_NAME_ASYNC_COMPLETE)
  @javax.annotation.Nullable
  private Boolean asyncComplete;

  public static final String SERIALIZED_NAME_START_DELAY_SECONDS = "startDelaySeconds";
  @SerializedName(SERIALIZED_NAME_START_DELAY_SECONDS)
  @javax.annotation.Nullable
  private BigDecimal startDelaySeconds;

  public static final String SERIALIZED_NAME_CACHE_CONFIG = "cacheConfig";
  @SerializedName(SERIALIZED_NAME_CACHE_CONFIG)
  @javax.annotation.Nullable
  private Shared2d711327d8CacheConfig cacheConfig;

  public static final String SERIALIZED_NAME_RETRY_COUNT = "retryCount";
  @SerializedName(SERIALIZED_NAME_RETRY_COUNT)
  @javax.annotation.Nullable
  private Integer retryCount;

  public static final String SERIALIZED_NAME_DOMAIN = "domain";
  @SerializedName(SERIALIZED_NAME_DOMAIN)
  @javax.annotation.Nullable
  private String domain;

  /**
   * Gets or Sets evaluatorType
   */
  @JsonAdapter(EvaluatorTypeEnum.Adapter.class)
  public enum EvaluatorTypeEnum {
    VALUE_PARAM("value-param"),
    
    JAVASCRIPT("javascript"),
    
    JSONPATH("jsonpath");

    private String value;

    EvaluatorTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static EvaluatorTypeEnum fromValue(String value) {
      for (EvaluatorTypeEnum b : EvaluatorTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<EvaluatorTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EvaluatorTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EvaluatorTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return EvaluatorTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      EvaluatorTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_EVALUATOR_TYPE = "evaluatorType";
  @SerializedName(SERIALIZED_NAME_EVALUATOR_TYPE)
  @javax.annotation.Nullable
  private EvaluatorTypeEnum evaluatorType;

  public static final String SERIALIZED_NAME_EXPRESSION = "expression";
  @SerializedName(SERIALIZED_NAME_EXPRESSION)
  @javax.annotation.Nullable
  private String expression;

  public static final String SERIALIZED_NAME_DECISION_CASES = "decisionCases";
  @SerializedName(SERIALIZED_NAME_DECISION_CASES)
  @javax.annotation.Nullable
  private Map<String, List<Shared2d711327d8>> decisionCases = new HashMap<>();

  public static final String SERIALIZED_NAME_DEFAULT_CASE = "defaultCase";
  @SerializedName(SERIALIZED_NAME_DEFAULT_CASE)
  @javax.annotation.Nullable
  private List<Shared2d711327d8> defaultCase = new ArrayList<>();

  public static final String SERIALIZED_NAME_FORK_TASKS = "forkTasks";
  @SerializedName(SERIALIZED_NAME_FORK_TASKS)
  @javax.annotation.Nullable
  private List<List<Shared2d711327d8>> forkTasks = new ArrayList<>();

  public static final String SERIALIZED_NAME_DYNAMIC_FORK_TASKS_PARAM = "dynamicForkTasksParam";
  @SerializedName(SERIALIZED_NAME_DYNAMIC_FORK_TASKS_PARAM)
  @javax.annotation.Nullable
  private String dynamicForkTasksParam;

  public static final String SERIALIZED_NAME_DYNAMIC_FORK_TASKS_INPUT_PARAM_NAME = "dynamicForkTasksInputParamName";
  @SerializedName(SERIALIZED_NAME_DYNAMIC_FORK_TASKS_INPUT_PARAM_NAME)
  @javax.annotation.Nullable
  private String dynamicForkTasksInputParamName;

  public static final String SERIALIZED_NAME_JOIN_ON = "joinOn";
  @SerializedName(SERIALIZED_NAME_JOIN_ON)
  @javax.annotation.Nullable
  private List<String> joinOn = new ArrayList<>();

  public static final String SERIALIZED_NAME_LOOP_CONDITION = "loopCondition";
  @SerializedName(SERIALIZED_NAME_LOOP_CONDITION)
  @javax.annotation.Nullable
  private String loopCondition;

  public static final String SERIALIZED_NAME_LOOP_OVER = "loopOver";
  @SerializedName(SERIALIZED_NAME_LOOP_OVER)
  @javax.annotation.Nullable
  private List<Shared2d711327d8> loopOver = new ArrayList<>();

  public static final String SERIALIZED_NAME_DYNAMIC_TASK_NAME_PARAM = "dynamicTaskNameParam";
  @SerializedName(SERIALIZED_NAME_DYNAMIC_TASK_NAME_PARAM)
  @javax.annotation.Nullable
  private String dynamicTaskNameParam;

  public static final String SERIALIZED_NAME_SUB_WORKFLOW_PARAM = "subWorkflowParam";
  @SerializedName(SERIALIZED_NAME_SUB_WORKFLOW_PARAM)
  @javax.annotation.Nullable
  private Shared2d711327d8SubWorkflowParam subWorkflowParam;

  public static final String SERIALIZED_NAME_COMPENSATE_WITH = "compensateWith";
  @SerializedName(SERIALIZED_NAME_COMPENSATE_WITH)
  @javax.annotation.Nullable
  private Shared2d711327d8CompensateWith compensateWith;

  public Shared2d711327d8() {
  }

  public Shared2d711327d8 name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public Shared2d711327d8 taskReferenceName(@javax.annotation.Nonnull String taskReferenceName) {
    this.taskReferenceName = taskReferenceName;
    return this;
  }

  /**
   * Get taskReferenceName
   * @return taskReferenceName
   */
  @javax.annotation.Nonnull
  public String getTaskReferenceName() {
    return taskReferenceName;
  }

  public void setTaskReferenceName(@javax.annotation.Nonnull String taskReferenceName) {
    this.taskReferenceName = taskReferenceName;
  }


  public Shared2d711327d8 type(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  public TypeEnum getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public Shared2d711327d8 description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public Shared2d711327d8 inputParameters(@javax.annotation.Nullable Map<String, Object> inputParameters) {
    this.inputParameters = inputParameters;
    return this;
  }

  public Shared2d711327d8 putInputParametersItem(String key, Object inputParametersItem) {
    if (this.inputParameters == null) {
      this.inputParameters = new HashMap<>();
    }
    this.inputParameters.put(key, inputParametersItem);
    return this;
  }

  /**
   * Get inputParameters
   * @return inputParameters
   */
  @javax.annotation.Nullable
  public Map<String, Object> getInputParameters() {
    return inputParameters;
  }

  public void setInputParameters(@javax.annotation.Nullable Map<String, Object> inputParameters) {
    this.inputParameters = inputParameters;
  }


  public Shared2d711327d8 optional(@javax.annotation.Nullable Boolean optional) {
    this.optional = optional;
    return this;
  }

  /**
   * Get optional
   * @return optional
   */
  @javax.annotation.Nullable
  public Boolean getOptional() {
    return optional;
  }

  public void setOptional(@javax.annotation.Nullable Boolean optional) {
    this.optional = optional;
  }


  public Shared2d711327d8 asyncComplete(@javax.annotation.Nullable Boolean asyncComplete) {
    this.asyncComplete = asyncComplete;
    return this;
  }

  /**
   * Get asyncComplete
   * @return asyncComplete
   */
  @javax.annotation.Nullable
  public Boolean getAsyncComplete() {
    return asyncComplete;
  }

  public void setAsyncComplete(@javax.annotation.Nullable Boolean asyncComplete) {
    this.asyncComplete = asyncComplete;
  }


  public Shared2d711327d8 startDelaySeconds(@javax.annotation.Nullable BigDecimal startDelaySeconds) {
    this.startDelaySeconds = startDelaySeconds;
    return this;
  }

  /**
   * Get startDelaySeconds
   * minimum: 0
   * @return startDelaySeconds
   */
  @javax.annotation.Nullable
  public BigDecimal getStartDelaySeconds() {
    return startDelaySeconds;
  }

  public void setStartDelaySeconds(@javax.annotation.Nullable BigDecimal startDelaySeconds) {
    this.startDelaySeconds = startDelaySeconds;
  }


  public Shared2d711327d8 cacheConfig(@javax.annotation.Nullable Shared2d711327d8CacheConfig cacheConfig) {
    this.cacheConfig = cacheConfig;
    return this;
  }

  /**
   * Get cacheConfig
   * @return cacheConfig
   */
  @javax.annotation.Nullable
  public Shared2d711327d8CacheConfig getCacheConfig() {
    return cacheConfig;
  }

  public void setCacheConfig(@javax.annotation.Nullable Shared2d711327d8CacheConfig cacheConfig) {
    this.cacheConfig = cacheConfig;
  }


  public Shared2d711327d8 retryCount(@javax.annotation.Nullable Integer retryCount) {
    this.retryCount = retryCount;
    return this;
  }

  /**
   * Get retryCount
   * minimum: 0
   * @return retryCount
   */
  @javax.annotation.Nullable
  public Integer getRetryCount() {
    return retryCount;
  }

  public void setRetryCount(@javax.annotation.Nullable Integer retryCount) {
    this.retryCount = retryCount;
  }


  public Shared2d711327d8 domain(@javax.annotation.Nullable String domain) {
    this.domain = domain;
    return this;
  }

  /**
   * Get domain
   * @return domain
   */
  @javax.annotation.Nullable
  public String getDomain() {
    return domain;
  }

  public void setDomain(@javax.annotation.Nullable String domain) {
    this.domain = domain;
  }


  public Shared2d711327d8 evaluatorType(@javax.annotation.Nullable EvaluatorTypeEnum evaluatorType) {
    this.evaluatorType = evaluatorType;
    return this;
  }

  /**
   * Get evaluatorType
   * @return evaluatorType
   */
  @javax.annotation.Nullable
  public EvaluatorTypeEnum getEvaluatorType() {
    return evaluatorType;
  }

  public void setEvaluatorType(@javax.annotation.Nullable EvaluatorTypeEnum evaluatorType) {
    this.evaluatorType = evaluatorType;
  }


  public Shared2d711327d8 expression(@javax.annotation.Nullable String expression) {
    this.expression = expression;
    return this;
  }

  /**
   * Get expression
   * @return expression
   */
  @javax.annotation.Nullable
  public String getExpression() {
    return expression;
  }

  public void setExpression(@javax.annotation.Nullable String expression) {
    this.expression = expression;
  }


  public Shared2d711327d8 decisionCases(@javax.annotation.Nullable Map<String, List<Shared2d711327d8>> decisionCases) {
    this.decisionCases = decisionCases;
    return this;
  }

  public Shared2d711327d8 putDecisionCasesItem(String key, List<Shared2d711327d8> decisionCasesItem) {
    if (this.decisionCases == null) {
      this.decisionCases = new HashMap<>();
    }
    this.decisionCases.put(key, decisionCasesItem);
    return this;
  }

  /**
   * Get decisionCases
   * @return decisionCases
   */
  @javax.annotation.Nullable
  public Map<String, List<Shared2d711327d8>> getDecisionCases() {
    return decisionCases;
  }

  public void setDecisionCases(@javax.annotation.Nullable Map<String, List<Shared2d711327d8>> decisionCases) {
    this.decisionCases = decisionCases;
  }


  public Shared2d711327d8 defaultCase(@javax.annotation.Nullable List<Shared2d711327d8> defaultCase) {
    this.defaultCase = defaultCase;
    return this;
  }

  public Shared2d711327d8 addDefaultCaseItem(Shared2d711327d8 defaultCaseItem) {
    if (this.defaultCase == null) {
      this.defaultCase = new ArrayList<>();
    }
    this.defaultCase.add(defaultCaseItem);
    return this;
  }

  /**
   * Get defaultCase
   * @return defaultCase
   */
  @javax.annotation.Nullable
  public List<Shared2d711327d8> getDefaultCase() {
    return defaultCase;
  }

  public void setDefaultCase(@javax.annotation.Nullable List<Shared2d711327d8> defaultCase) {
    this.defaultCase = defaultCase;
  }


  public Shared2d711327d8 forkTasks(@javax.annotation.Nullable List<List<Shared2d711327d8>> forkTasks) {
    this.forkTasks = forkTasks;
    return this;
  }

  public Shared2d711327d8 addForkTasksItem(List<Shared2d711327d8> forkTasksItem) {
    if (this.forkTasks == null) {
      this.forkTasks = new ArrayList<>();
    }
    this.forkTasks.add(forkTasksItem);
    return this;
  }

  /**
   * Get forkTasks
   * @return forkTasks
   */
  @javax.annotation.Nullable
  public List<List<Shared2d711327d8>> getForkTasks() {
    return forkTasks;
  }

  public void setForkTasks(@javax.annotation.Nullable List<List<Shared2d711327d8>> forkTasks) {
    this.forkTasks = forkTasks;
  }


  public Shared2d711327d8 dynamicForkTasksParam(@javax.annotation.Nullable String dynamicForkTasksParam) {
    this.dynamicForkTasksParam = dynamicForkTasksParam;
    return this;
  }

  /**
   * Get dynamicForkTasksParam
   * @return dynamicForkTasksParam
   */
  @javax.annotation.Nullable
  public String getDynamicForkTasksParam() {
    return dynamicForkTasksParam;
  }

  public void setDynamicForkTasksParam(@javax.annotation.Nullable String dynamicForkTasksParam) {
    this.dynamicForkTasksParam = dynamicForkTasksParam;
  }


  public Shared2d711327d8 dynamicForkTasksInputParamName(@javax.annotation.Nullable String dynamicForkTasksInputParamName) {
    this.dynamicForkTasksInputParamName = dynamicForkTasksInputParamName;
    return this;
  }

  /**
   * Get dynamicForkTasksInputParamName
   * @return dynamicForkTasksInputParamName
   */
  @javax.annotation.Nullable
  public String getDynamicForkTasksInputParamName() {
    return dynamicForkTasksInputParamName;
  }

  public void setDynamicForkTasksInputParamName(@javax.annotation.Nullable String dynamicForkTasksInputParamName) {
    this.dynamicForkTasksInputParamName = dynamicForkTasksInputParamName;
  }


  public Shared2d711327d8 joinOn(@javax.annotation.Nullable List<String> joinOn) {
    this.joinOn = joinOn;
    return this;
  }

  public Shared2d711327d8 addJoinOnItem(String joinOnItem) {
    if (this.joinOn == null) {
      this.joinOn = new ArrayList<>();
    }
    this.joinOn.add(joinOnItem);
    return this;
  }

  /**
   * Get joinOn
   * @return joinOn
   */
  @javax.annotation.Nullable
  public List<String> getJoinOn() {
    return joinOn;
  }

  public void setJoinOn(@javax.annotation.Nullable List<String> joinOn) {
    this.joinOn = joinOn;
  }


  public Shared2d711327d8 loopCondition(@javax.annotation.Nullable String loopCondition) {
    this.loopCondition = loopCondition;
    return this;
  }

  /**
   * Get loopCondition
   * @return loopCondition
   */
  @javax.annotation.Nullable
  public String getLoopCondition() {
    return loopCondition;
  }

  public void setLoopCondition(@javax.annotation.Nullable String loopCondition) {
    this.loopCondition = loopCondition;
  }


  public Shared2d711327d8 loopOver(@javax.annotation.Nullable List<Shared2d711327d8> loopOver) {
    this.loopOver = loopOver;
    return this;
  }

  public Shared2d711327d8 addLoopOverItem(Shared2d711327d8 loopOverItem) {
    if (this.loopOver == null) {
      this.loopOver = new ArrayList<>();
    }
    this.loopOver.add(loopOverItem);
    return this;
  }

  /**
   * Get loopOver
   * @return loopOver
   */
  @javax.annotation.Nullable
  public List<Shared2d711327d8> getLoopOver() {
    return loopOver;
  }

  public void setLoopOver(@javax.annotation.Nullable List<Shared2d711327d8> loopOver) {
    this.loopOver = loopOver;
  }


  public Shared2d711327d8 dynamicTaskNameParam(@javax.annotation.Nullable String dynamicTaskNameParam) {
    this.dynamicTaskNameParam = dynamicTaskNameParam;
    return this;
  }

  /**
   * Get dynamicTaskNameParam
   * @return dynamicTaskNameParam
   */
  @javax.annotation.Nullable
  public String getDynamicTaskNameParam() {
    return dynamicTaskNameParam;
  }

  public void setDynamicTaskNameParam(@javax.annotation.Nullable String dynamicTaskNameParam) {
    this.dynamicTaskNameParam = dynamicTaskNameParam;
  }


  public Shared2d711327d8 subWorkflowParam(@javax.annotation.Nullable Shared2d711327d8SubWorkflowParam subWorkflowParam) {
    this.subWorkflowParam = subWorkflowParam;
    return this;
  }

  /**
   * Get subWorkflowParam
   * @return subWorkflowParam
   */
  @javax.annotation.Nullable
  public Shared2d711327d8SubWorkflowParam getSubWorkflowParam() {
    return subWorkflowParam;
  }

  public void setSubWorkflowParam(@javax.annotation.Nullable Shared2d711327d8SubWorkflowParam subWorkflowParam) {
    this.subWorkflowParam = subWorkflowParam;
  }


  public Shared2d711327d8 compensateWith(@javax.annotation.Nullable Shared2d711327d8CompensateWith compensateWith) {
    this.compensateWith = compensateWith;
    return this;
  }

  /**
   * Get compensateWith
   * @return compensateWith
   */
  @javax.annotation.Nullable
  public Shared2d711327d8CompensateWith getCompensateWith() {
    return compensateWith;
  }

  public void setCompensateWith(@javax.annotation.Nullable Shared2d711327d8CompensateWith compensateWith) {
    this.compensateWith = compensateWith;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Shared2d711327d8 shared2d711327d8 = (Shared2d711327d8) o;
    return Objects.equals(this.name, shared2d711327d8.name) &&
        Objects.equals(this.taskReferenceName, shared2d711327d8.taskReferenceName) &&
        Objects.equals(this.type, shared2d711327d8.type) &&
        Objects.equals(this.description, shared2d711327d8.description) &&
        Objects.equals(this.inputParameters, shared2d711327d8.inputParameters) &&
        Objects.equals(this.optional, shared2d711327d8.optional) &&
        Objects.equals(this.asyncComplete, shared2d711327d8.asyncComplete) &&
        Objects.equals(this.startDelaySeconds, shared2d711327d8.startDelaySeconds) &&
        Objects.equals(this.cacheConfig, shared2d711327d8.cacheConfig) &&
        Objects.equals(this.retryCount, shared2d711327d8.retryCount) &&
        Objects.equals(this.domain, shared2d711327d8.domain) &&
        Objects.equals(this.evaluatorType, shared2d711327d8.evaluatorType) &&
        Objects.equals(this.expression, shared2d711327d8.expression) &&
        Objects.equals(this.decisionCases, shared2d711327d8.decisionCases) &&
        Objects.equals(this.defaultCase, shared2d711327d8.defaultCase) &&
        Objects.equals(this.forkTasks, shared2d711327d8.forkTasks) &&
        Objects.equals(this.dynamicForkTasksParam, shared2d711327d8.dynamicForkTasksParam) &&
        Objects.equals(this.dynamicForkTasksInputParamName, shared2d711327d8.dynamicForkTasksInputParamName) &&
        Objects.equals(this.joinOn, shared2d711327d8.joinOn) &&
        Objects.equals(this.loopCondition, shared2d711327d8.loopCondition) &&
        Objects.equals(this.loopOver, shared2d711327d8.loopOver) &&
        Objects.equals(this.dynamicTaskNameParam, shared2d711327d8.dynamicTaskNameParam) &&
        Objects.equals(this.subWorkflowParam, shared2d711327d8.subWorkflowParam) &&
        Objects.equals(this.compensateWith, shared2d711327d8.compensateWith);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, taskReferenceName, type, description, inputParameters, optional, asyncComplete, startDelaySeconds, cacheConfig, retryCount, domain, evaluatorType, expression, decisionCases, defaultCase, forkTasks, dynamicForkTasksParam, dynamicForkTasksInputParamName, joinOn, loopCondition, loopOver, dynamicTaskNameParam, subWorkflowParam, compensateWith);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Shared2d711327d8 {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    taskReferenceName: ").append(toIndentedString(taskReferenceName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    inputParameters: ").append(toIndentedString(inputParameters)).append("\n");
    sb.append("    optional: ").append(toIndentedString(optional)).append("\n");
    sb.append("    asyncComplete: ").append(toIndentedString(asyncComplete)).append("\n");
    sb.append("    startDelaySeconds: ").append(toIndentedString(startDelaySeconds)).append("\n");
    sb.append("    cacheConfig: ").append(toIndentedString(cacheConfig)).append("\n");
    sb.append("    retryCount: ").append(toIndentedString(retryCount)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    evaluatorType: ").append(toIndentedString(evaluatorType)).append("\n");
    sb.append("    expression: ").append(toIndentedString(expression)).append("\n");
    sb.append("    decisionCases: ").append(toIndentedString(decisionCases)).append("\n");
    sb.append("    defaultCase: ").append(toIndentedString(defaultCase)).append("\n");
    sb.append("    forkTasks: ").append(toIndentedString(forkTasks)).append("\n");
    sb.append("    dynamicForkTasksParam: ").append(toIndentedString(dynamicForkTasksParam)).append("\n");
    sb.append("    dynamicForkTasksInputParamName: ").append(toIndentedString(dynamicForkTasksInputParamName)).append("\n");
    sb.append("    joinOn: ").append(toIndentedString(joinOn)).append("\n");
    sb.append("    loopCondition: ").append(toIndentedString(loopCondition)).append("\n");
    sb.append("    loopOver: ").append(toIndentedString(loopOver)).append("\n");
    sb.append("    dynamicTaskNameParam: ").append(toIndentedString(dynamicTaskNameParam)).append("\n");
    sb.append("    subWorkflowParam: ").append(toIndentedString(subWorkflowParam)).append("\n");
    sb.append("    compensateWith: ").append(toIndentedString(compensateWith)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "taskReferenceName", "type", "description", "inputParameters", "optional", "asyncComplete", "startDelaySeconds", "cacheConfig", "retryCount", "domain", "evaluatorType", "expression", "decisionCases", "defaultCase", "forkTasks", "dynamicForkTasksParam", "dynamicForkTasksInputParamName", "joinOn", "loopCondition", "loopOver", "dynamicTaskNameParam", "subWorkflowParam", "compensateWith"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("name", "taskReferenceName", "type"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Shared2d711327d8
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Shared2d711327d8.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in Shared2d711327d8 is not found in the empty JSON string", Shared2d711327d8.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Shared2d711327d8.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Shared2d711327d8` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Shared2d711327d8.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("taskReferenceName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `taskReferenceName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("taskReferenceName").toString()));
      }
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // validate the required field `type`
      TypeEnum.validateJsonElement(jsonObj.get("type"));
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      // validate the optional field `cacheConfig`
      if (jsonObj.get("cacheConfig") != null && !jsonObj.get("cacheConfig").isJsonNull()) {
        Shared2d711327d8CacheConfig.validateJsonElement(jsonObj.get("cacheConfig"));
      }
      if ((jsonObj.get("domain") != null && !jsonObj.get("domain").isJsonNull()) && !jsonObj.get("domain").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `domain` to be a primitive type in the JSON string but got `%s`", jsonObj.get("domain").toString()));
      }
      if ((jsonObj.get("evaluatorType") != null && !jsonObj.get("evaluatorType").isJsonNull()) && !jsonObj.get("evaluatorType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `evaluatorType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("evaluatorType").toString()));
      }
      // validate the optional field `evaluatorType`
      if (jsonObj.get("evaluatorType") != null && !jsonObj.get("evaluatorType").isJsonNull()) {
        EvaluatorTypeEnum.validateJsonElement(jsonObj.get("evaluatorType"));
      }
      if ((jsonObj.get("expression") != null && !jsonObj.get("expression").isJsonNull()) && !jsonObj.get("expression").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `expression` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expression").toString()));
      }
      if (jsonObj.get("defaultCase") != null && !jsonObj.get("defaultCase").isJsonNull()) {
        JsonArray jsonArraydefaultCase = jsonObj.getAsJsonArray("defaultCase");
        if (jsonArraydefaultCase != null) {
          // ensure the json data is an array
          if (!jsonObj.get("defaultCase").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `defaultCase` to be an array in the JSON string but got `%s`", jsonObj.get("defaultCase").toString()));
          }

          // validate the optional field `defaultCase` (array)
          for (int i = 0; i < jsonArraydefaultCase.size(); i++) {
            Shared2d711327d8.validateJsonElement(jsonArraydefaultCase.get(i));
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("forkTasks") != null && !jsonObj.get("forkTasks").isJsonNull() && !jsonObj.get("forkTasks").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `forkTasks` to be an array in the JSON string but got `%s`", jsonObj.get("forkTasks").toString()));
      }
      if ((jsonObj.get("dynamicForkTasksParam") != null && !jsonObj.get("dynamicForkTasksParam").isJsonNull()) && !jsonObj.get("dynamicForkTasksParam").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `dynamicForkTasksParam` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dynamicForkTasksParam").toString()));
      }
      if ((jsonObj.get("dynamicForkTasksInputParamName") != null && !jsonObj.get("dynamicForkTasksInputParamName").isJsonNull()) && !jsonObj.get("dynamicForkTasksInputParamName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `dynamicForkTasksInputParamName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dynamicForkTasksInputParamName").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("joinOn") != null && !jsonObj.get("joinOn").isJsonNull() && !jsonObj.get("joinOn").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `joinOn` to be an array in the JSON string but got `%s`", jsonObj.get("joinOn").toString()));
      }
      if ((jsonObj.get("loopCondition") != null && !jsonObj.get("loopCondition").isJsonNull()) && !jsonObj.get("loopCondition").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `loopCondition` to be a primitive type in the JSON string but got `%s`", jsonObj.get("loopCondition").toString()));
      }
      if (jsonObj.get("loopOver") != null && !jsonObj.get("loopOver").isJsonNull()) {
        JsonArray jsonArrayloopOver = jsonObj.getAsJsonArray("loopOver");
        if (jsonArrayloopOver != null) {
          // ensure the json data is an array
          if (!jsonObj.get("loopOver").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `loopOver` to be an array in the JSON string but got `%s`", jsonObj.get("loopOver").toString()));
          }

          // validate the optional field `loopOver` (array)
          for (int i = 0; i < jsonArrayloopOver.size(); i++) {
            Shared2d711327d8.validateJsonElement(jsonArrayloopOver.get(i));
          };
        }
      }
      if ((jsonObj.get("dynamicTaskNameParam") != null && !jsonObj.get("dynamicTaskNameParam").isJsonNull()) && !jsonObj.get("dynamicTaskNameParam").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `dynamicTaskNameParam` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dynamicTaskNameParam").toString()));
      }
      // validate the optional field `subWorkflowParam`
      if (jsonObj.get("subWorkflowParam") != null && !jsonObj.get("subWorkflowParam").isJsonNull()) {
        Shared2d711327d8SubWorkflowParam.validateJsonElement(jsonObj.get("subWorkflowParam"));
      }
      // validate the optional field `compensateWith`
      if (jsonObj.get("compensateWith") != null && !jsonObj.get("compensateWith").isJsonNull()) {
        Shared2d711327d8CompensateWith.validateJsonElement(jsonObj.get("compensateWith"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Shared2d711327d8.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Shared2d711327d8' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Shared2d711327d8> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Shared2d711327d8.class));

       return (TypeAdapter<T>) new TypeAdapter<Shared2d711327d8>() {
           @Override
           public void write(JsonWriter out, Shared2d711327d8 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Shared2d711327d8 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Shared2d711327d8 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Shared2d711327d8
   * @throws IOException if the JSON string is invalid with respect to Shared2d711327d8
   */
  public static Shared2d711327d8 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Shared2d711327d8.class);
  }

  /**
   * Convert an instance of Shared2d711327d8 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

