/* tslint:disable */
/* eslint-disable */
/**
 * node-flow
 * Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface GroupAddMemberRequest {
    ns: string;
    name: string;
}

export interface GroupCreateRequest {
    ns: string;
}

export interface GroupGetRequest {
    ns: string;
    name: string;
}

export interface GroupListRequest {
    ns: string;
}

export interface GroupRemoveRequest {
    ns: string;
    name: string;
}

export interface GroupRemoveMemberRequest {
    ns: string;
    name: string;
    userId: string;
}

export interface GroupSetScopesRequest {
    ns: string;
    name: string;
}

export interface GroupSetTagGrantsRequest {
    ns: string;
    name: string;
}

/**
 * 
 */
export class GroupsApi extends runtime.BaseAPI {

    /**
     * Add someone to a group
     */
    async groupAddMemberRaw(requestParameters: GroupAddMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling groupAddMember().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling groupAddMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/groups/{name}/members`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add someone to a group
     */
    async groupAddMember(requestParameters: GroupAddMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.groupAddMemberRaw(requestParameters, initOverrides);
    }

    /**
     * Create a group
     */
    async groupCreateRaw(requestParameters: GroupCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling groupCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/groups`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create a group
     */
    async groupCreate(requestParameters: GroupCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.groupCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetch a group and its members
     */
    async groupGetRaw(requestParameters: GroupGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling groupGet().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling groupGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/groups/{name}`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Fetch a group and its members
     */
    async groupGet(requestParameters: GroupGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.groupGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List groups
     */
    async groupListRaw(requestParameters: GroupListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling groupList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/groups`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List groups
     */
    async groupList(requestParameters: GroupListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.groupListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a group
     */
    async groupRemoveRaw(requestParameters: GroupRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling groupRemove().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling groupRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/groups/{name}`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a group
     */
    async groupRemove(requestParameters: GroupRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.groupRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Remove someone from a group
     */
    async groupRemoveMemberRaw(requestParameters: GroupRemoveMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling groupRemoveMember().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling groupRemoveMember().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling groupRemoveMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/groups/{name}/members/{userId}`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove someone from a group
     */
    async groupRemoveMember(requestParameters: GroupRemoveMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.groupRemoveMemberRaw(requestParameters, initOverrides);
    }

    /**
     * Takes effect for every member on their next request, since a principal resolves its scopes each time rather than caching them into a session.
     * Replace a group’s scopes
     */
    async groupSetScopesRaw(requestParameters: GroupSetScopesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling groupSetScopes().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling groupSetScopes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/groups/{name}/scopes`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Takes effect for every member on their next request, since a principal resolves its scopes each time rather than caching them into a session.
     * Replace a group’s scopes
     */
    async groupSetScopes(requestParameters: GroupSetScopesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.groupSetScopesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Tags restrict, they never grant: an untagged resource is governed by scopes alone, and a tagged one additionally needs a matching grant. Patterns match literally or by trailing wildcard, exactly like scopes.
     * Replace the tag patterns this group’s members may reach
     */
    async groupSetTagGrantsRaw(requestParameters: GroupSetTagGrantsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling groupSetTagGrants().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling groupSetTagGrants().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/groups/{name}/tag-grants`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Tags restrict, they never grant: an untagged resource is governed by scopes alone, and a tagged one additionally needs a matching grant. Patterns match literally or by trailing wildcard, exactly like scopes.
     * Replace the tag patterns this group’s members may reach
     */
    async groupSetTagGrants(requestParameters: GroupSetTagGrantsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.groupSetTagGrantsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
