/* tslint:disable */
/* eslint-disable */
/**
 * node-flow
 * Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MetadataExportBundleRequest,
  MetadataImportBpmnDocumentRequest,
  MetadataImportBundleRequest,
  MetadataRegisterWorkflowRequest,
  MetadataSetWorkflowTagsRequest,
  MetadataUpsertTaskDefinitionRequest,
  SimulationTestRequest,
} from '../models/index';
import {
    MetadataExportBundleRequestFromJSON,
    MetadataExportBundleRequestToJSON,
    MetadataImportBpmnDocumentRequestFromJSON,
    MetadataImportBpmnDocumentRequestToJSON,
    MetadataImportBundleRequestFromJSON,
    MetadataImportBundleRequestToJSON,
    MetadataRegisterWorkflowRequestFromJSON,
    MetadataRegisterWorkflowRequestToJSON,
    MetadataSetWorkflowTagsRequestFromJSON,
    MetadataSetWorkflowTagsRequestToJSON,
    MetadataUpsertTaskDefinitionRequestFromJSON,
    MetadataUpsertTaskDefinitionRequestToJSON,
    SimulationTestRequestFromJSON,
    SimulationTestRequestToJSON,
} from '../models/index';

export interface MetadataDeleteTaskDefinitionRequest {
    ns: string;
    name: string;
}

export interface MetadataDeleteWorkflowRequest {
    ns: string;
    name: string;
    version: number;
}

export interface MetadataExportBundleOperationRequest {
    ns: string;
    metadataExportBundleRequest: MetadataExportBundleRequest;
}

export interface MetadataGetTaskDefinitionRequest {
    ns: string;
    name: string;
}

export interface MetadataGetWorkflowRequest {
    ns: string;
    name: string;
    version?: number;
}

export interface MetadataImportBpmnDocumentOperationRequest {
    ns: string;
    metadataImportBpmnDocumentRequest: MetadataImportBpmnDocumentRequest;
}

export interface MetadataImportBundleOperationRequest {
    ns: string;
    metadataImportBundleRequest: MetadataImportBundleRequest;
}

export interface MetadataListTaskDefinitionsRequest {
    ns: string;
}

export interface MetadataListWorkflowsRequest {
    ns: string;
}

export interface MetadataRegisterWorkflowOperationRequest {
    ns: string;
    metadataRegisterWorkflowRequest: MetadataRegisterWorkflowRequest;
}

export interface MetadataSetWorkflowTagsOperationRequest {
    ns: string;
    name: string;
    metadataSetWorkflowTagsRequest: MetadataSetWorkflowTagsRequest;
}

export interface MetadataUpsertTaskDefinitionOperationRequest {
    ns: string;
    metadataUpsertTaskDefinitionRequest: MetadataUpsertTaskDefinitionRequest;
}

export interface MetadataValidateWorkflowRequest {
    ns: string;
}

export interface SimulationTestOperationRequest {
    ns: string;
    simulationTestRequest: SimulationTestRequest;
}

/**
 * 
 */
export class MetadataApi extends runtime.BaseAPI {

    /**
     * Refused with 409 while tasks of this type are queued or running: they would silently lose their retry and timeout policy mid-flight.
     * Delete a task definition
     */
    async metadataDeleteTaskDefinitionRaw(requestParameters: MetadataDeleteTaskDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling metadataDeleteTaskDefinition().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling metadataDeleteTaskDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/metadata/task-definitions/{name}`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Refused with 409 while tasks of this type are queued or running: they would silently lose their retry and timeout policy mid-flight.
     * Delete a task definition
     */
    async metadataDeleteTaskDefinition(requestParameters: MetadataDeleteTaskDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.metadataDeleteTaskDefinitionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Refused with 409 while any execution of that version is still running: running executions reload their definition, and deleting it would strand them.
     * Delete one version of a workflow definition
     */
    async metadataDeleteWorkflowRaw(requestParameters: MetadataDeleteWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling metadataDeleteWorkflow().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling metadataDeleteWorkflow().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling metadataDeleteWorkflow().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['version'] != null) {
            queryParameters['version'] = requestParameters['version'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/metadata/workflows/{name}`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Refused with 409 while any execution of that version is still running: running executions reload their definition, and deleting it would strand them.
     * Delete one version of a workflow definition
     */
    async metadataDeleteWorkflow(requestParameters: MetadataDeleteWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.metadataDeleteWorkflowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Everything reachable when `workflows` is omitted. With `includeDependencies` (the default), the sub-workflows, started workflows and failure workflows a workflow names come along, with the task definitions its worker tasks use. Tag-protected workflows you cannot reach are left out.
     * Export workflows and task definitions as one JSON bundle
     */
    async metadataExportBundleRaw(requestParameters: MetadataExportBundleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling metadataExportBundle().'
            );
        }

        if (requestParameters['metadataExportBundleRequest'] == null) {
            throw new runtime.RequiredError(
                'metadataExportBundleRequest',
                'Required parameter "metadataExportBundleRequest" was null or undefined when calling metadataExportBundle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/metadata/export`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MetadataExportBundleRequestToJSON(requestParameters['metadataExportBundleRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Everything reachable when `workflows` is omitted. With `includeDependencies` (the default), the sub-workflows, started workflows and failure workflows a workflow names come along, with the task definitions its worker tasks use. Tag-protected workflows you cannot reach are left out.
     * Export workflows and task definitions as one JSON bundle
     */
    async metadataExportBundle(requestParameters: MetadataExportBundleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.metadataExportBundleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a task definition
     */
    async metadataGetTaskDefinitionRaw(requestParameters: MetadataGetTaskDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling metadataGetTaskDefinition().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling metadataGetTaskDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/metadata/task-definitions/{name}`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get a task definition
     */
    async metadataGetTaskDefinition(requestParameters: MetadataGetTaskDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.metadataGetTaskDefinitionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetch one workflow definition
     */
    async metadataGetWorkflowRaw(requestParameters: MetadataGetWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling metadataGetWorkflow().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling metadataGetWorkflow().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['version'] != null) {
            queryParameters['version'] = requestParameters['version'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/metadata/workflows/{name}`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Fetch one workflow definition
     */
    async metadataGetWorkflow(requestParameters: MetadataGetWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.metadataGetWorkflowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a draft definition and the warnings that came with it — loops, unmatched gateways, elements with no equivalent. Nothing is registered: review the draft and save it like any other.
     * Convert a BPMN 2.0 process into a workflow definition
     */
    async metadataImportBpmnDocumentRaw(requestParameters: MetadataImportBpmnDocumentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling metadataImportBpmnDocument().'
            );
        }

        if (requestParameters['metadataImportBpmnDocumentRequest'] == null) {
            throw new runtime.RequiredError(
                'metadataImportBpmnDocumentRequest',
                'Required parameter "metadataImportBpmnDocumentRequest" was null or undefined when calling metadataImportBpmnDocument().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/metadata/workflows/import-bpmn`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MetadataImportBpmnDocumentRequestToJSON(requestParameters['metadataImportBpmnDocumentRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Returns a draft definition and the warnings that came with it — loops, unmatched gateways, elements with no equivalent. Nothing is registered: review the draft and save it like any other.
     * Convert a BPMN 2.0 process into a workflow definition
     */
    async metadataImportBpmnDocument(requestParameters: MetadataImportBpmnDocumentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.metadataImportBpmnDocumentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The whole bundle is validated before anything is written; if any definition is invalid, nothing is imported and the report says which. An existing workflow version is `unchanged` when identical, otherwise skipped or registered as the next version (`workflowConflicts`); an existing task definition is skipped or overwritten (`taskDefinitionConflicts`). `dryRun` reports without writing. Requests are limited to 1 MB; split larger bundles.
     * Import a bundle of workflows and task definitions
     */
    async metadataImportBundleRaw(requestParameters: MetadataImportBundleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling metadataImportBundle().'
            );
        }

        if (requestParameters['metadataImportBundleRequest'] == null) {
            throw new runtime.RequiredError(
                'metadataImportBundleRequest',
                'Required parameter "metadataImportBundleRequest" was null or undefined when calling metadataImportBundle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/metadata/import`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MetadataImportBundleRequestToJSON(requestParameters['metadataImportBundleRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * The whole bundle is validated before anything is written; if any definition is invalid, nothing is imported and the report says which. An existing workflow version is `unchanged` when identical, otherwise skipped or registered as the next version (`workflowConflicts`); an existing task definition is skipped or overwritten (`taskDefinitionConflicts`). `dryRun` reports without writing. Requests are limited to 1 MB; split larger bundles.
     * Import a bundle of workflows and task definitions
     */
    async metadataImportBundle(requestParameters: MetadataImportBundleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.metadataImportBundleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List task definitions
     */
    async metadataListTaskDefinitionsRaw(requestParameters: MetadataListTaskDefinitionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling metadataListTaskDefinitions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/metadata/task-definitions`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List task definitions
     */
    async metadataListTaskDefinitions(requestParameters: MetadataListTaskDefinitionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.metadataListTaskDefinitionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List registered workflows
     */
    async metadataListWorkflowsRaw(requestParameters: MetadataListWorkflowsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling metadataListWorkflows().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/metadata/workflows`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List registered workflows
     */
    async metadataListWorkflows(requestParameters: MetadataListWorkflowsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.metadataListWorkflowsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Validated and compiled on registration, so a definition that cannot run is a 400 at deploy time rather than a failure at 3am on an unexercised branch. Versions are immutable once registered.
     * Register a workflow definition
     */
    async metadataRegisterWorkflowRaw(requestParameters: MetadataRegisterWorkflowOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling metadataRegisterWorkflow().'
            );
        }

        if (requestParameters['metadataRegisterWorkflowRequest'] == null) {
            throw new runtime.RequiredError(
                'metadataRegisterWorkflowRequest',
                'Required parameter "metadataRegisterWorkflowRequest" was null or undefined when calling metadataRegisterWorkflow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/metadata/workflows`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MetadataRegisterWorkflowRequestToJSON(requestParameters['metadataRegisterWorkflowRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Validated and compiled on registration, so a definition that cannot run is a 400 at deploy time rather than a failure at 3am on an unexercised branch. Versions are immutable once registered.
     * Register a workflow definition
     */
    async metadataRegisterWorkflow(requestParameters: MetadataRegisterWorkflowOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.metadataRegisterWorkflowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Applies to every version: tags protect a workflow by name. Tags restrict, never grant — a tagged workflow is reachable only by principals holding a matching tag grant.
     * Replace the tags on a workflow
     */
    async metadataSetWorkflowTagsRaw(requestParameters: MetadataSetWorkflowTagsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling metadataSetWorkflowTags().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling metadataSetWorkflowTags().'
            );
        }

        if (requestParameters['metadataSetWorkflowTagsRequest'] == null) {
            throw new runtime.RequiredError(
                'metadataSetWorkflowTagsRequest',
                'Required parameter "metadataSetWorkflowTagsRequest" was null or undefined when calling metadataSetWorkflowTags().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/metadata/workflows/{name}/tags`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MetadataSetWorkflowTagsRequestToJSON(requestParameters['metadataSetWorkflowTagsRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Applies to every version: tags protect a workflow by name. Tags restrict, never grant — a tagged workflow is reachable only by principals holding a matching tag grant.
     * Replace the tags on a workflow
     */
    async metadataSetWorkflowTags(requestParameters: MetadataSetWorkflowTagsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.metadataSetWorkflowTagsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unlike workflows, task definitions are mutable.
     * Create or update a task definition
     */
    async metadataUpsertTaskDefinitionRaw(requestParameters: MetadataUpsertTaskDefinitionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling metadataUpsertTaskDefinition().'
            );
        }

        if (requestParameters['metadataUpsertTaskDefinitionRequest'] == null) {
            throw new runtime.RequiredError(
                'metadataUpsertTaskDefinitionRequest',
                'Required parameter "metadataUpsertTaskDefinitionRequest" was null or undefined when calling metadataUpsertTaskDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/metadata/task-definitions`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MetadataUpsertTaskDefinitionRequestToJSON(requestParameters['metadataUpsertTaskDefinitionRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Unlike workflows, task definitions are mutable.
     * Create or update a task definition
     */
    async metadataUpsertTaskDefinition(requestParameters: MetadataUpsertTaskDefinitionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.metadataUpsertTaskDefinitionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a verdict, not an error: `valid`, and on failure the issues with a path or task reference locating each one. Uses the same check as registration.
     * Validate and compile a workflow definition without registering it
     */
    async metadataValidateWorkflowRaw(requestParameters: MetadataValidateWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling metadataValidateWorkflow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/metadata/workflows/validate`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Returns a verdict, not an error: `valid`, and on failure the issues with a path or task reference locating each one. Uses the same check as registration.
     * Validate and compile a workflow definition without registering it
     */
    async metadataValidateWorkflow(requestParameters: MetadataValidateWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.metadataValidateWorkflowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Runs the definition through the real engine, in memory. Tasks with effects take their outcome from `mocks` (by task reference; an array gives one outcome per attempt). Nothing is persisted or published.
     * Test a workflow with mocked task outcomes
     */
    async simulationTestRaw(requestParameters: SimulationTestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling simulationTest().'
            );
        }

        if (requestParameters['simulationTestRequest'] == null) {
            throw new runtime.RequiredError(
                'simulationTestRequest',
                'Required parameter "simulationTestRequest" was null or undefined when calling simulationTest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/metadata/workflows/test`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SimulationTestRequestToJSON(requestParameters['simulationTestRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Runs the definition through the real engine, in memory. Tasks with effects take their outcome from `mocks` (by task reference; an array gives one outcome per attempt). Nothing is persisted or published.
     * Test a workflow with mocked task outcomes
     */
    async simulationTest(requestParameters: SimulationTestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.simulationTestRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
