/* tslint:disable */
/* eslint-disable */
/**
 * node-flow
 * Workflow orchestration. Definitions are declarative JSON; workers are language-agnostic and lease tasks from a queue.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  IncomingWebhookCreateRequest,
  IncomingWebhookUpdateRequest,
} from '../models/index';
import {
    IncomingWebhookCreateRequestFromJSON,
    IncomingWebhookCreateRequestToJSON,
    IncomingWebhookUpdateRequestFromJSON,
    IncomingWebhookUpdateRequestToJSON,
} from '../models/index';

export interface HookReceiverReceiveRequest {
    id: string;
}

export interface IncomingWebhookCreateOperationRequest {
    ns: string;
    incomingWebhookCreateRequest: IncomingWebhookCreateRequest;
}

export interface IncomingWebhookGetRequest {
    ns: string;
    name: string;
}

export interface IncomingWebhookListRequest {
    ns: string;
}

export interface IncomingWebhookRemoveRequest {
    ns: string;
    name: string;
}

export interface IncomingWebhookUpdateOperationRequest {
    ns: string;
    name: string;
    incomingWebhookUpdateRequest: IncomingWebhookUpdateRequest;
}

export interface WebhookDeliverRequest {
    ns: string;
    token: string;
}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI {

    /**
     * Receive a webhook delivery
     */
    async hookReceiverReceiveRaw(requestParameters: HookReceiverReceiveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hookReceiverReceive().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/hooks/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Receive a webhook delivery
     */
    async hookReceiverReceive(requestParameters: HookReceiverReceiveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.hookReceiverReceiveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create an inbound webhook
     */
    async incomingWebhookCreateRaw(requestParameters: IncomingWebhookCreateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling incomingWebhookCreate().'
            );
        }

        if (requestParameters['incomingWebhookCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'incomingWebhookCreateRequest',
                'Required parameter "incomingWebhookCreateRequest" was null or undefined when calling incomingWebhookCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/incoming-webhooks`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IncomingWebhookCreateRequestToJSON(requestParameters['incomingWebhookCreateRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create an inbound webhook
     */
    async incomingWebhookCreate(requestParameters: IncomingWebhookCreateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.incomingWebhookCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetch an inbound webhook
     */
    async incomingWebhookGetRaw(requestParameters: IncomingWebhookGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling incomingWebhookGet().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling incomingWebhookGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/incoming-webhooks/{name}`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Fetch an inbound webhook
     */
    async incomingWebhookGet(requestParameters: IncomingWebhookGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.incomingWebhookGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List inbound webhooks
     */
    async incomingWebhookListRaw(requestParameters: IncomingWebhookListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling incomingWebhookList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/incoming-webhooks`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List inbound webhooks
     */
    async incomingWebhookList(requestParameters: IncomingWebhookListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.incomingWebhookListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an inbound webhook
     */
    async incomingWebhookRemoveRaw(requestParameters: IncomingWebhookRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling incomingWebhookRemove().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling incomingWebhookRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/incoming-webhooks/{name}`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an inbound webhook
     */
    async incomingWebhookRemove(requestParameters: IncomingWebhookRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.incomingWebhookRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Update an inbound webhook
     */
    async incomingWebhookUpdateRaw(requestParameters: IncomingWebhookUpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling incomingWebhookUpdate().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling incomingWebhookUpdate().'
            );
        }

        if (requestParameters['incomingWebhookUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'incomingWebhookUpdateRequest',
                'Required parameter "incomingWebhookUpdateRequest" was null or undefined when calling incomingWebhookUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ns/{ns}/incoming-webhooks/{name}`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: IncomingWebhookUpdateRequestToJSON(requestParameters['incomingWebhookUpdateRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update an inbound webhook
     */
    async incomingWebhookUpdate(requestParameters: IncomingWebhookUpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.incomingWebhookUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Public by design: the unguessable token is the capability, and it completes exactly one task. Single-use, so a retried delivery is a 409 rather than a second completion.
     * Deliver a callback to a waiting WAIT_FOR_WEBHOOK task
     */
    async webhookDeliverRaw(requestParameters: WebhookDeliverRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['ns'] == null) {
            throw new runtime.RequiredError(
                'ns',
                'Required parameter "ns" was null or undefined when calling webhookDeliver().'
            );
        }

        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling webhookDeliver().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/ns/{ns}/webhooks/{token}`;
        urlPath = urlPath.replace(`{${"ns"}}`, encodeURIComponent(String(requestParameters['ns'])));
        urlPath = urlPath.replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Public by design: the unguessable token is the capability, and it completes exactly one task. Single-use, so a retried delivery is a 409 rather than a second completion.
     * Deliver a callback to a waiting WAIT_FOR_WEBHOOK task
     */
    async webhookDeliver(requestParameters: WebhookDeliverRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.webhookDeliverRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
